const content = {
  "en": {
    "Home": {
      "metaTitle": "Free Online Tools & Calculators - Antigravity",
      "metaDescription": "Access a comprehensive collection of free online tools, unit converters, calculators, and developer utilities. No signup required. Fast, private, and accurate.",
      "heroH1": "Free Online Tools for Every Need",
      "heroSub": "Discover our collection of fast, private, and highly accurate free online tools, calculators, and converters to simplify your daily tasks.",
      "trustFree": "100% Free",
      "trustNoSignup": "No Signup",
      "trustBrowser": "Runs in Browser",
      "trustLanguages": "16 Languages",
      "searchPlaceholder": "Search calculators, converters...",
      "popular": "Popular:",
      "browseCategories": "Browse by Category",
      "browseCategoriesDesc": "Explore our extensive library of web utilities categorized for your convenience. From finance to web development, find exactly what you need.",
      "mostPopularTools": "Most Popular Tools",
      "mostPopularToolsDesc": "Join thousands of users who rely on these highly-rated free online tools for their daily mathematical and conversion needs.",
      "exploreAll": "Explore All Tools",
      "whyUse": "Why Choose Our Platform?",
      "whyUseDesc": "We prioritize user experience above all else. Our platform is engineered to deliver instant results without compromising your digital privacy or data security.",
      "featureSpeedTitle": "Lightning Fast Processing",
      "featureSpeedDesc": "All calculations are performed locally in your browser. Experience zero lag, instant conversions, and no waiting for server responses.",
      "featurePrivacyTitle": "Strict Privacy Standards",
      "featurePrivacyDesc": "We do not store your input data. Your information never leaves your device, ensuring complete confidentiality for sensitive financial or personal calculations.",
      "featureAccuracyTitle": "High Precision Accuracy",
      "featureAccuracyDesc": "Our algorithms use standardized, globally accepted formulas. Whether you're calculating taxes or converting scientific units, expect rigorous precision.",
      "howItWorksTitle": "How It Works in 3 Steps",
      "howItWorksStep1": "Find your tool",
      "howItWorksStep1Desc": "Use the smart search bar or browse through our well-organized categories to locate the specific calculator or converter you need.",
      "howItWorksStep2": "Enter your data",
      "howItWorksStep2Desc": "Input your numbers, text, or dates into our intuitive, user-friendly interface designed for both desktop and mobile devices.",
      "howItWorksStep3": "Get instant results",
      "howItWorksStep3Desc": "View your accurate results instantly. Copy them to your clipboard with a single click or export them for your personal records.",
      "featuredTool": "Featured Tool of the Week",
      "featuredToolDesc": "Try our comprehensive Age Calculator to find out your exact age in years, months, days, and even seconds with absolute precision.",
      "featuredToolCTA": "Try the Age Calculator",
      "languagesTitle": "Available in 16 Languages",
      "languagesDesc": "We believe powerful utilities should be accessible to everyone. Switch to your preferred native language for a seamless localized experience.",
      "faqTitle": "Frequently Asked Questions",
      "faq1Q": "Are these online tools completely free to use?",
      "faq1A": "Yes, absolutely. Our entire suite of calculators, converters, and developer utilities is 100% free. There are no hidden fees, premium tiers, or subscription requirements.",
      "faq2Q": "Do I need to create an account to use the calculators?",
      "faq2A": "No signup or registration is required. You can access and utilize every feature on our website immediately upon visiting, without handing over any personal information.",
      "faq3Q": "Is my data stored on your servers?",
      "faq3A": "No. The vast majority of our tools process data locally within your web browser. We do not collect, store, or transmit your inputted numbers or text to external servers.",
      "faq4Q": "How accurate are the financial calculators?",
      "faq4A": "Our financial tools are built using standard accounting formulas and are regularly audited. However, they are for informational purposes and should not replace professional financial advice.",
      "faq5Q": "Can I use this website on my mobile phone?",
      "faq5A": "Yes, our platform is fully responsive. It is optimized to work perfectly on smartphones, tablets, and desktop computers, providing a consistent experience across all devices.",
      "faq6Q": "How often are new tools added?",
      "faq6A": "We continuously expand our directory. New calculators and utilities are added weekly based on user feedback and emerging trends in web development and daily productivity.",
      "ctaTitle": "Ready to simplify your tasks?",
      "ctaDesc": "Stop wasting time doing manual calculations. Start using our free online tools today and boost your daily productivity.",
      "ctaButton": "View All Categories"
    }
  },
  "es": {
    "Home": {
      "metaTitle": "Herramientas Online Gratis y Calculadoras",
      "metaDescription": "Accede a una colección completa de herramientas online gratis, convertidores de unidades y utilidades web. Sin registro. Rápido, privado y preciso.",
      "heroH1": "Herramientas Online Gratis para Cada Necesidad",
      "heroSub": "Descubre nuestra colección de calculadoras y convertidores en línea, diseñados para ser rápidos, precisos y proteger tu privacidad en cada tarea diaria.",
      "trustFree": "100% Gratis",
      "trustNoSignup": "Sin Registro",
      "trustBrowser": "Uso en Navegador",
      "trustLanguages": "16 Idiomas",
      "searchPlaceholder": "Buscar calculadoras, convertidores...",
      "popular": "Popular:",
      "browseCategories": "Explorar por Categoría",
      "browseCategoriesDesc": "Navega por nuestra amplia biblioteca de utilidades web organizadas por categorías. Desde finanzas hasta desarrollo web, encuentra exactamente lo que buscas.",
      "mostPopularTools": "Herramientas Más Populares",
      "mostPopularToolsDesc": "Únete a miles de usuarios que confían en estas herramientas online gratis para resolver sus necesidades matemáticas y de conversión todos los días.",
      "exploreAll": "Explorar Todas",
      "whyUse": "¿Por Qué Elegir Nuestra Plataforma?",
      "whyUseDesc": "Priorizamos la experiencia del usuario. Nuestra plataforma está construida para ofrecer resultados instantáneos sin comprometer tu privacidad digital ni la seguridad de tus datos.",
      "featureSpeedTitle": "Procesamiento Ultrarrápido",
      "featureSpeedDesc": "Todos los cálculos se ejecutan localmente en tu navegador. Experimenta cero demoras, conversiones al instante y sin esperas por respuestas del servidor.",
      "featurePrivacyTitle": "Estrictos Estándares de Privacidad",
      "featurePrivacyDesc": "No almacenamos los datos que introduces. Tu información nunca sale de tu dispositivo, asegurando total confidencialidad para cálculos sensibles.",
      "featureAccuracyTitle": "Precisión de Alta Fidelidad",
      "featureAccuracyDesc": "Nuestros algoritmos utilizan fórmulas estandarizadas a nivel global. Ya sea para calcular impuestos o convertir unidades científicas, espera una precisión rigurosa.",
      "howItWorksTitle": "Cómo Funciona en 3 Pasos",
      "howItWorksStep1": "Encuentra tu herramienta",
      "howItWorksStep1Desc": "Usa la barra de búsqueda inteligente o explora nuestras categorías bien organizadas para localizar la calculadora o convertidor específico que necesitas.",
      "howItWorksStep2": "Introduce tus datos",
      "howItWorksStep2Desc": "Ingresa tus números, textos o fechas en nuestra interfaz intuitiva, diseñada tanto para ordenadores de escritorio como para dispositivos móviles.",
      "howItWorksStep3": "Obtén resultados al instante",
      "howItWorksStep3Desc": "Visualiza tus resultados de manera precisa e inmediata. Cópialos al portapapeles con un solo clic o expórtalos para tus registros personales.",
      "featuredTool": "Herramienta Destacada de la Semana",
      "featuredToolDesc": "Prueba nuestra completa Calculadora de Edad para averiguar tu edad exacta en años, meses, días e incluso segundos con total precisión.",
      "featuredToolCTA": "Probar la Calculadora de Edad",
      "languagesTitle": "Disponible en 16 Idiomas",
      "languagesDesc": "Creemos que las utilidades potentes deben ser accesibles para todos. Cambia a tu idioma nativo para disfrutar de una experiencia perfectamente localizada.",
      "faqTitle": "Preguntas Frecuentes",
      "faq1Q": "¿El uso de estas herramientas es completamente gratuito?",
      "faq1A": "Sí, absolutamente. Toda nuestra gama de calculadoras, convertidores y utilidades para desarrolladores es 100% gratis. No hay tarifas ocultas ni suscripciones.",
      "faq2Q": "¿Necesito crear una cuenta para usar las calculadoras?",
      "faq2A": "No se requiere ningún tipo de registro. Puedes acceder y utilizar todas las funciones de nuestro sitio web inmediatamente, sin proporcionar información personal.",
      "faq3Q": "¿Se almacenan mis datos en sus servidores?",
      "faq3A": "No. La gran mayoría de nuestras herramientas procesan los datos localmente en tu navegador web. No recopilamos, almacenamos ni transmitimos tu información a servidores externos.",
      "faq4Q": "¿Qué tan precisas son las calculadoras financieras?",
      "faq4A": "Nuestras herramientas financieras utilizan fórmulas contables estándar y son auditadas regularmente. Sin embargo, tienen fines informativos y no sustituyen el asesoramiento financiero profesional.",
      "faq5Q": "¿Puedo usar este sitio web en mi teléfono móvil?",
      "faq5A": "Sí, nuestra plataforma es totalmente responsiva. Está optimizada para funcionar a la perfección en teléfonos inteligentes, tabletas y ordenadores de escritorio.",
      "faq6Q": "¿Con qué frecuencia se añaden nuevas herramientas?",
      "faq6A": "Ampliamos nuestro directorio continuamente. Añadimos nuevas calculadoras y utilidades cada semana, basándonos en los comentarios de los usuarios y las tendencias actuales.",
      "ctaTitle": "¿Listo para simplificar tus tareas?",
      "ctaDesc": "Deja de perder tiempo haciendo cálculos manuales. Empieza a usar nuestras herramientas online gratis hoy mismo y aumenta tu productividad.",
      "ctaButton": "Ver Todas las Categorías"
    }
  },
  "fr": {
    "Home": {
      "metaTitle": "Outils en Ligne Gratuits & Calculatrices",
      "metaDescription": "Accédez à une collection complète d'outils en ligne gratuits, convertisseurs d'unités et utilitaires web. Sans inscription. Rapide, privé et précis.",
      "heroH1": "Outils en Ligne Gratuits pour Tous vos Besoins",
      "heroSub": "Découvrez notre collection de calculatrices et convertisseurs en ligne rapides, privés et précis pour simplifier vos tâches quotidiennes.",
      "trustFree": "100% Gratuit",
      "trustNoSignup": "Sans Inscription",
      "trustBrowser": "Exécution Locale",
      "trustLanguages": "16 Langues",
      "searchPlaceholder": "Rechercher des calculatrices...",
      "popular": "Populaire :",
      "browseCategories": "Parcourir par Catégorie",
      "browseCategoriesDesc": "Explorez notre vaste bibliothèque d'utilitaires web classés par catégorie. De la finance au développement web, trouvez exactement ce qu'il vous faut.",
      "mostPopularTools": "Outils les Plus Populaires",
      "mostPopularToolsDesc": "Rejoignez des milliers d'utilisateurs qui font confiance à ces outils en ligne gratuits pour leurs calculs quotidiens et besoins de conversion.",
      "exploreAll": "Tout Explorer",
      "whyUse": "Pourquoi Choisir Notre Plateforme ?",
      "whyUseDesc": "Nous privilégions l'expérience utilisateur avant tout. Notre plateforme est conçue pour fournir des résultats instantanés sans compromettre votre confidentialité numérique.",
      "featureSpeedTitle": "Traitement Ultra-rapide",
      "featureSpeedDesc": "Tous les calculs sont effectués localement dans votre navigateur. Profitez d'une absence de latence, de conversions instantanées et d'aucun temps d'attente.",
      "featurePrivacyTitle": "Normes de Confidentialité Strictes",
      "featurePrivacyDesc": "Nous ne stockons pas vos données saisies. Vos informations ne quittent jamais votre appareil, garantissant une confidentialité totale pour vos calculs sensibles.",
      "featureAccuracyTitle": "Précision de Haute Fidélité",
      "featureAccuracyDesc": "Nos algorithmes utilisent des formules standardisées mondialement. Qu'il s'agisse de calculs fiscaux ou de conversions scientifiques, attendez-vous à une précision rigoureuse.",
      "howItWorksTitle": "Comment ça Marche en 3 Étapes",
      "howItWorksStep1": "Trouvez votre outil",
      "howItWorksStep1Desc": "Utilisez la barre de recherche intelligente ou parcourez nos catégories bien organisées pour trouver la calculatrice ou le convertisseur dont vous avez besoin.",
      "howItWorksStep2": "Saisissez vos données",
      "howItWorksStep2Desc": "Entrez vos nombres, textes ou dates dans notre interface intuitive et conviviale, conçue aussi bien pour les ordinateurs que pour les mobiles.",
      "howItWorksStep3": "Obtenez des résultats instantanés",
      "howItWorksStep3Desc": "Visualisez vos résultats instantanément et avec précision. Copiez-les dans votre presse-papiers en un clic ou exportez-les pour vos dossiers.",
      "featuredTool": "Outil en Vedette de la Semaine",
      "featuredToolDesc": "Essayez notre Calculateur d'Âge complet pour connaître votre âge exact en années, mois, jours et même secondes avec une précision absolue.",
      "featuredToolCTA": "Essayer le Calculateur d'Âge",
      "languagesTitle": "Disponible en 16 Langues",
      "languagesDesc": "Nous pensons que de puissants utilitaires doivent être accessibles à tous. Passez à votre langue maternelle pour une expérience localisée fluide.",
      "faqTitle": "Foire Aux Questions",
      "faq1Q": "Ces outils en ligne sont-ils totalement gratuits ?",
      "faq1A": "Oui, absolument. L'ensemble de nos calculatrices, convertisseurs et utilitaires est 100 % gratuit. Il n'y a pas de frais cachés ni d'abonnements requis.",
      "faq2Q": "Dois-je créer un compte pour utiliser les calculatrices ?",
      "faq2A": "Aucune inscription n'est requise. Vous pouvez accéder à toutes les fonctionnalités de notre site web immédiatement, sans fournir la moindre information personnelle.",
      "faq3Q": "Mes données sont-elles stockées sur vos serveurs ?",
      "faq3A": "Non. La grande majorité de nos outils traitent les données localement dans votre navigateur. Nous ne collectons, ni ne stockons vos chiffres ou textes sur nos serveurs.",
      "faq4Q": "Quelle est la précision des calculatrices financières ?",
      "faq4A": "Nos outils financiers reposent sur des formules comptables standards et sont régulièrement audités. Cependant, ils sont fournis à titre informatif et ne remplacent pas un avis professionnel.",
      "faq5Q": "Puis-je utiliser ce site sur mon téléphone mobile ?",
      "faq5A": "Oui, notre plateforme est entièrement responsive. Elle est optimisée pour fonctionner parfaitement sur les smartphones, tablettes et ordinateurs de bureau.",
      "faq6Q": "À quelle fréquence de nouveaux outils sont-ils ajoutés ?",
      "faq6A": "Nous élargissons continuellement notre annuaire. De nouvelles calculatrices et utilitaires sont ajoutés chaque semaine en fonction des retours de nos utilisateurs.",
      "ctaTitle": "Prêt à simplifier vos tâches ?",
      "ctaDesc": "Arrêtez de perdre du temps avec des calculs manuels. Commencez à utiliser nos outils en ligne gratuits dès aujourd'hui et boostez votre productivité.",
      "ctaButton": "Voir Toutes les Catégories"
    }
  },
  "de": {
    "Home": {
      "metaTitle": "Kostenlose Online-Tools & Rechner",
      "metaDescription": "Greifen Sie auf eine umfassende Sammlung kostenloser Online-Tools, Einheitenumrechner und Web-Utilities zu. Keine Anmeldung. Schnell, privat und genau.",
      "heroH1": "Kostenlose Online-Tools für jeden Bedarf",
      "heroSub": "Entdecken Sie unsere Sammlung schneller, privater und präziser Online-Rechner und Konverter, um Ihre täglichen Aufgaben zu vereinfachen.",
      "trustFree": "100% Kostenlos",
      "trustNoSignup": "Ohne Anmeldung",
      "trustBrowser": "Läuft im Browser",
      "trustLanguages": "16 Sprachen",
      "searchPlaceholder": "Rechner oder Konverter suchen...",
      "popular": "Beliebt:",
      "browseCategories": "Nach Kategorie durchsuchen",
      "browseCategoriesDesc": "Erkunden Sie unsere umfangreiche Bibliothek an Web-Utilities, übersichtlich in Kategorien unterteilt. Finden Sie genau das, was Sie suchen.",
      "mostPopularTools": "Beliebteste Tools",
      "mostPopularToolsDesc": "Schließen Sie sich Tausenden von Nutzern an, die sich täglich auf diese erstklassigen, kostenlosen Online-Tools für Berechnungen und Konvertierungen verlassen.",
      "exploreAll": "Alle ansehen",
      "whyUse": "Warum unsere Plattform wählen?",
      "whyUseDesc": "Die Benutzererfahrung steht bei uns an erster Stelle. Unsere Plattform ist darauf ausgelegt, sofortige Ergebnisse zu liefern, ohne Ihre digitale Privatsphäre zu gefährden.",
      "featureSpeedTitle": "Blitzschnelle Verarbeitung",
      "featureSpeedDesc": "Alle Berechnungen werden lokal in Ihrem Browser durchgeführt. Erleben Sie null Verzögerung, sofortige Konvertierungen und keine Wartezeiten auf Serverantworten.",
      "featurePrivacyTitle": "Strenge Datenschutzstandards",
      "featurePrivacyDesc": "Wir speichern Ihre Eingabedaten nicht. Ihre Informationen verlassen niemals Ihr Gerät, was bei sensiblen Berechnungen absolute Vertraulichkeit garantiert.",
      "featureAccuracyTitle": "Hohe Präzision",
      "featureAccuracyDesc": "Unsere Algorithmen verwenden standardisierte, global anerkannte Formeln. Erwarten Sie bei steuerlichen Berechnungen oder wissenschaftlichen Umrechnungen höchste Präzision.",
      "howItWorksTitle": "So funktioniert es in 3 Schritten",
      "howItWorksStep1": "Finden Sie Ihr Tool",
      "howItWorksStep1Desc": "Nutzen Sie die intelligente Suchleiste oder durchsuchen Sie unsere gut organisierten Kategorien, um den spezifischen Rechner oder Konverter zu finden.",
      "howItWorksStep2": "Geben Sie Ihre Daten ein",
      "howItWorksStep2Desc": "Geben Sie Ihre Zahlen, Texte oder Daten in unsere intuitive und benutzerfreundliche Oberfläche ein, die für Desktop- und Mobilgeräte konzipiert ist.",
      "howItWorksStep3": "Erhalten Sie sofortige Ergebnisse",
      "howItWorksStep3Desc": "Sehen Sie Ihre Ergebnisse sofort und präzise. Kopieren Sie sie mit einem einzigen Klick in die Zwischenablage oder exportieren Sie sie.",
      "featuredTool": "Hervorgehobenes Tool der Woche",
      "featuredToolDesc": "Probieren Sie unseren umfassenden Altersrechner aus, um Ihr genaues Alter in Jahren, Monaten, Tagen und sogar Sekunden zu ermitteln.",
      "featuredToolCTA": "Altersrechner ausprobieren",
      "languagesTitle": "Verfügbar in 16 Sprachen",
      "languagesDesc": "Wir glauben, dass leistungsstarke Dienstprogramme für jeden zugänglich sein sollten. Wechseln Sie für ein nahtloses Erlebnis zu Ihrer Muttersprache.",
      "faqTitle": "Häufig gestellte Fragen",
      "faq1Q": "Sind diese Online-Tools wirklich völlig kostenlos?",
      "faq1A": "Ja, absolut. Unsere gesamte Palette an Rechnern, Konvertern und Entwickler-Tools ist zu 100 % kostenlos. Es gibt keine versteckten Gebühren oder Abonnements.",
      "faq2Q": "Muss ich ein Konto erstellen, um die Rechner zu nutzen?",
      "faq2A": "Es ist keine Anmeldung oder Registrierung erforderlich. Sie können alle Funktionen unserer Website sofort nutzen, ohne persönliche Daten anzugeben.",
      "faq3Q": "Werden meine Daten auf Ihren Servern gespeichert?",
      "faq3A": "Nein. Die große Mehrheit unserer Tools verarbeitet Daten lokal in Ihrem Webbrowser. Wir sammeln oder speichern Ihre eingegebenen Zahlen und Texte nicht extern.",
      "faq4Q": "Wie genau sind die Finanzrechner?",
      "faq4A": "Unsere Finanz-Tools basieren auf standardisierten Buchhaltungsformeln und werden regelmäßig geprüft. Sie dienen jedoch nur zu Informationszwecken und ersetzen keine professionelle Beratung.",
      "faq5Q": "Kann ich diese Website auf meinem Handy nutzen?",
      "faq5A": "Ja, unsere Plattform ist vollständig responsiv. Sie ist so optimiert, dass sie auf Smartphones, Tablets und Desktop-Computern einwandfrei funktioniert.",
      "faq6Q": "Wie oft werden neue Tools hinzugefügt?",
      "faq6A": "Wir erweitern unser Verzeichnis kontinuierlich. Jede Woche werden neue Rechner und Utilities basierend auf Nutzerfeedback und neuen Trends hinzugefügt.",
      "ctaTitle": "Bereit, Ihre Aufgaben zu vereinfachen?",
      "ctaDesc": "Verschwenden Sie keine Zeit mehr mit manuellen Berechnungen. Beginnen Sie noch heute mit der Nutzung unserer kostenlosen Online-Tools.",
      "ctaButton": "Alle Kategorien ansehen"
    }
  }
};

import fs from 'fs';
for (const lang of Object.keys(content)) {
  const filePath = `messages/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data.Home = content[lang].Home;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}`);
  }
}
