const content = {
  "hi": {
    "Home": {
      "metaTitle": "मुफ़्त ऑनलाइन टूल और कैलकुलेटर - 100 Tools",
      "metaDescription": "मुफ़्त ऑनलाइन टूल्स, यूनिट कन्वर्टर और वेब यूटिलिटीज़ के एक व्यापक संग्रह तक पहुँचें। बिना साइनअप के। तेज़, सुरक्षित और सटीक।",
      "heroH1": "हर ज़रूरत के लिए मुफ़्त ऑनलाइन टूल",
      "heroSub": "अपने दैनिक कार्यों को सरल बनाने के लिए तेज़, सुरक्षित और अत्यधिक सटीक ऑनलाइन कैलकुलेटर और कन्वर्टर्स के हमारे संग्रह की खोज करें।",
      "trustFree": "100% मुफ़्त",
      "trustNoSignup": "कोई साइनअप नहीं",
      "trustBrowser": "ब्राउज़र में चलता है",
      "trustLanguages": "16 भाषाएँ",
      "searchPlaceholder": "कैलकुलेटर, कन्वर्टर खोजें...",
      "popular": "लोकप्रिय:",
      "browseCategories": "श्रेणी के अनुसार ब्राउज़ करें",
      "browseCategoriesDesc": "अपनी सुविधा के लिए वर्गीकृत हमारे वेब उपयोगिताओं के व्यापक पुस्तकालय का अन्वेषण करें। वित्त से लेकर वेब विकास तक, आपको जो चाहिए वह खोजें।",
      "mostPopularTools": "सबसे लोकप्रिय टूल",
      "mostPopularToolsDesc": "उन हज़ारों उपयोगकर्ताओं से जुड़ें जो अपनी दैनिक गणितीय और रूपांतरण आवश्यकताओं के लिए इन उच्च-रेटेड मुफ़्त ऑनलाइन टूल पर भरोसा करते हैं।",
      "exploreAll": "सभी टूल देखें",
      "whyUse": "हमारा प्लेटफ़ॉर्म क्यों चुनें?",
      "whyUseDesc": "हम उपयोगकर्ता के अनुभव को सबसे ऊपर प्राथमिकता देते हैं। हमारा प्लेटफ़ॉर्म आपकी डिजिटल गोपनीयता से समझौता किए बिना त्वरित परिणाम देने के लिए डिज़ाइन किया गया है।",
      "featureSpeedTitle": "बिजली जैसी तेज़ प्रोसेसिंग",
      "featureSpeedDesc": "सभी गणनाएँ आपके ब्राउज़र में स्थानीय रूप से की जाती हैं। कोई अंतराल नहीं, तत्काल रूपांतरण और सर्वर प्रतिक्रिया के लिए कोई प्रतीक्षा नहीं।",
      "featurePrivacyTitle": "सख्त गोपनीयता मानक",
      "featurePrivacyDesc": "हम आपका इनपुट डेटा संग्रहीत नहीं करते हैं। आपकी जानकारी कभी भी आपका डिवाइस नहीं छोड़ती है, जिससे पूर्ण गोपनीयता सुनिश्चित होती है।",
      "featureAccuracyTitle": "उच्च परिशुद्धता सटीकता",
      "featureAccuracyDesc": "हमारे एल्गोरिदम मानकीकृत, विश्व स्तर पर स्वीकृत फ़ार्मुलों का उपयोग करते हैं। करों की गणना करते समय सटीक सटीकता की अपेक्षा करें।",
      "howItWorksTitle": "यह 3 चरणों में कैसे काम करता है",
      "howItWorksStep1": "अपना टूल खोजें",
      "howItWorksStep1Desc": "अपने आवश्यक विशिष्ट कैलकुलेटर या कनवर्टर का पता लगाने के लिए स्मार्ट सर्च बार का उपयोग करें या हमारी श्रेणियों के माध्यम से ब्राउज़ करें।",
      "howItWorksStep2": "अपना डेटा दर्ज करें",
      "howItWorksStep2Desc": "डेस्कटॉप और मोबाइल उपकरणों दोनों के लिए डिज़ाइन किए गए हमारे सहज ज्ञान युक्त इंटरफ़ेस में अपने नंबर, टेक्स्ट या दिनांक इनपुट करें।",
      "howItWorksStep3": "तत्काल परिणाम प्राप्त करें",
      "howItWorksStep3Desc": "तुरंत अपने सटीक परिणाम देखें। उन्हें एक क्लिक से अपने क्लिपबोर्ड पर कॉपी करें या अपने व्यक्तिगत रिकॉर्ड के लिए निर्यात करें।",
      "featuredTool": "सप्ताह का चुनिंदा टूल",
      "featuredToolDesc": "पूर्ण सटीकता के साथ वर्षों, महीनों, दिनों और यहां तक ​​कि सेकंडों में अपनी सटीक आयु का पता लगाने के लिए हमारे व्यापक आयु कैलकुलेटर का प्रयास करें।",
      "featuredToolCTA": "आयु कैलकुलेटर आज़माएं",
      "languagesTitle": "16 भाषाओं में उपलब्ध",
      "languagesDesc": "हमारा मानना ​​है कि शक्तिशाली उपकरण सभी के लिए सुलभ होने चाहिए। एक सहज अनुभव के लिए अपनी मूल भाषा में स्विच करें।",
      "faqTitle": "अक्सर पूछे जाने वाले प्रश्न",
      "faq1Q": "क्या इन ऑनलाइन टूल का उपयोग करना पूरी तरह से मुफ़्त है?",
      "faq1A": "हाँ, बिल्कुल। हमारे कैलकुलेटर, कनवर्टर और डेवलपर यूटिलिटीज़ का पूरा सूट 100% मुफ़्त है। कोई छिपी हुई फीस या सदस्यता की आवश्यकता नहीं है।",
      "faq2Q": "क्या मुझे कैलकुलेटर का उपयोग करने के लिए खाता बनाना होगा?",
      "faq2A": "किसी साइनअप या पंजीकरण की आवश्यकता नहीं है। आप कोई व्यक्तिगत जानकारी दिए बिना तुरंत हमारी वेबसाइट पर प्रत्येक सुविधा का उपयोग कर सकते हैं।",
      "faq3Q": "क्या मेरा डेटा आपके सर्वर पर संग्रहीत है?",
      "faq3A": "नहीं। हमारे अधिकांश टूल डेटा को आपके वेब ब्राउज़र में स्थानीय रूप से संसाधित करते हैं। हम आपका इनपुट किया गया डेटा संग्रहीत नहीं करते हैं।",
      "faq4Q": "वित्तीय कैलकुलेटर कितने सटीक हैं?",
      "faq4A": "हमारे वित्तीय उपकरण मानक लेखांकन सूत्रों का उपयोग करके बनाए गए हैं। हालांकि, वे पेशेवर वित्तीय सलाह को प्रतिस्थापित नहीं करते हैं।",
      "faq5Q": "क्या मैं अपने मोबाइल फोन पर इस वेबसाइट का उपयोग कर सकता हूं?",
      "faq5A": "हां, हमारा प्लेटफॉर्म स्मार्टफोन, टैबलेट और डेस्कटॉप कंप्यूटर पर पूरी तरह से काम करने के लिए अनुकूलित है।",
      "faq6Q": "नए टूल कितनी बार जोड़े जाते हैं?",
      "faq6A": "हम लगातार अपनी निर्देशिका का विस्तार करते हैं। उपयोगकर्ताओं की प्रतिक्रिया के आधार पर हर सप्ताह नए कैलकुलेटर और उपयोगिताओं को जोड़ा जाता है।",
      "ctaTitle": "क्या आप अपने कार्यों को सरल बनाने के लिए तैयार हैं?",
      "ctaDesc": "मैन्युअल गणना करने में समय बर्बाद करना बंद करें। आज ही हमारे मुफ़्त ऑनलाइन टूल का उपयोग करना शुरू करें और अपनी उत्पादकता बढ़ाएं।",
      "ctaButton": "सभी श्रेणियां देखें"
    }
  },
  "id": {
    "Home": {
      "metaTitle": "Alat Online Gratis & Kalkulator",
      "metaDescription": "Akses koleksi komprehensif alat online gratis, konverter satuan, dan utilitas web. Tanpa daftar. Cepat, privat, dan akurat.",
      "heroH1": "Alat Online Gratis untuk Setiap Kebutuhan",
      "heroSub": "Temukan koleksi kalkulator dan konverter online yang cepat, privat, dan sangat akurat untuk menyederhanakan tugas harian Anda.",
      "trustFree": "100% Gratis",
      "trustNoSignup": "Tanpa Daftar",
      "trustBrowser": "Berjalan di Browser",
      "trustLanguages": "16 Bahasa",
      "searchPlaceholder": "Cari kalkulator, konverter...",
      "popular": "Populer:",
      "browseCategories": "Telusuri Berdasarkan Kategori",
      "browseCategoriesDesc": "Jelajahi perpustakaan luas utilitas web kami yang dikategorikan untuk kenyamanan Anda. Dari keuangan hingga pengembangan web.",
      "mostPopularTools": "Alat Paling Populer",
      "mostPopularToolsDesc": "Bergabunglah dengan ribuan pengguna yang mengandalkan alat online gratis berperingkat tinggi ini untuk kebutuhan konversi harian mereka.",
      "exploreAll": "Jelajahi Semua",
      "whyUse": "Mengapa Memilih Platform Kami?",
      "whyUseDesc": "Kami memprioritaskan pengalaman pengguna. Platform kami dirancang untuk memberikan hasil instan tanpa mengorbankan privasi digital Anda.",
      "featureSpeedTitle": "Pemrosesan Sekilat Cahaya",
      "featureSpeedDesc": "Semua perhitungan dilakukan secara lokal di browser Anda. Rasakan tanpa jeda, konversi instan, dan tidak perlu menunggu respons server.",
      "featurePrivacyTitle": "Standar Privasi Ketat",
      "featurePrivacyDesc": "Kami tidak menyimpan data input Anda. Informasi Anda tidak pernah meninggalkan perangkat Anda, memastikan kerahasiaan lengkap.",
      "featureAccuracyTitle": "Akurasi Presisi Tinggi",
      "featureAccuracyDesc": "Algoritma kami menggunakan rumus terstandarisasi. Baik menghitung pajak atau mengonversi satuan ilmiah, harapkan presisi yang ketat.",
      "howItWorksTitle": "Cara Kerja dalam 3 Langkah",
      "howItWorksStep1": "Temukan alat Anda",
      "howItWorksStep1Desc": "Gunakan bilah pencarian cerdas atau telusuri kategori kami yang tertata rapi untuk menemukan kalkulator tertentu yang Anda butuhkan.",
      "howItWorksStep2": "Masukkan data Anda",
      "howItWorksStep2Desc": "Masukkan angka, teks, atau tanggal ke dalam antarmuka kami yang intuitif dan mudah digunakan, dirancang untuk desktop dan seluler.",
      "howItWorksStep3": "Dapatkan hasil instan",
      "howItWorksStep3Desc": "Lihat hasil akurat Anda secara instan. Salin ke clipboard Anda dengan satu klik atau ekspor untuk catatan pribadi Anda.",
      "featuredTool": "Alat Unggulan Minggu Ini",
      "featuredToolDesc": "Coba Kalkulator Usia komprehensif kami untuk mengetahui usia pasti Anda dalam tahun, bulan, hari, dan bahkan detik secara akurat.",
      "featuredToolCTA": "Coba Kalkulator Usia",
      "languagesTitle": "Tersedia dalam 16 Bahasa",
      "languagesDesc": "Kami percaya utilitas canggih harus dapat diakses oleh semua orang. Beralih ke bahasa asli Anda untuk pengalaman yang mulus.",
      "faqTitle": "Pertanyaan yang Sering Diajukan",
      "faq1Q": "Apakah alat online ini benar-benar gratis untuk digunakan?",
      "faq1A": "Ya, tentu saja. Seluruh kalkulator, konverter, dan utilitas kami 100% gratis. Tidak ada biaya tersembunyi atau langganan.",
      "faq2Q": "Apakah saya perlu membuat akun untuk menggunakan kalkulator?",
      "faq2A": "Tidak diperlukan pendaftaran. Anda dapat mengakses semua fitur di situs web kami segera tanpa memberikan informasi pribadi.",
      "faq3Q": "Apakah data saya disimpan di server Anda?",
      "faq3A": "Tidak. Sebagian besar alat kami memproses data secara lokal dalam browser web Anda. Kami tidak mengumpulkan angka yang Anda masukkan.",
      "faq4Q": "Seberapa akurat kalkulator keuangan?",
      "faq4A": "Alat keuangan kami dibangun menggunakan rumus akuntansi standar. Namun, alat tersebut bukan pengganti nasihat keuangan profesional.",
      "faq5Q": "Bolehkah saya menggunakan situs web ini di ponsel saya?",
      "faq5A": "Ya, platform kami sangat responsif. Ini dioptimalkan agar berfungsi sempurna di ponsel cerdas, tablet, dan komputer desktop.",
      "faq6Q": "Seberapa sering alat baru ditambahkan?",
      "faq6A": "Kami terus memperluas direktori kami. Kalkulator baru ditambahkan setiap minggu berdasarkan umpan balik dari pengguna.",
      "ctaTitle": "Siap untuk menyederhanakan tugas Anda?",
      "ctaDesc": "Berhentilah membuang-buang waktu melakukan perhitungan manual. Mulai gunakan alat online gratis kami hari ini dan tingkatkan produktivitas Anda.",
      "ctaButton": "Lihat Semua Kategori"
    }
  },
  "ja": {
    "Home": {
      "metaTitle": "無料オンラインツールと電卓",
      "metaDescription": "無料のオンラインツール、単位変換、開発者ユーティリティの包括的なコレクションにアクセスします。登録不要。高速、プライバシー保護、高精度。",
      "heroH1": "あらゆるニーズに対応する無料オンラインツール",
      "heroSub": "日々のタスクを簡素化する、高速でプライバシーが守られ、非常に正確なオンライン電卓とコンバーターのコレクションをご覧ください。",
      "trustFree": "完全無料",
      "trustNoSignup": "登録不要",
      "trustBrowser": "ブラウザで実行",
      "trustLanguages": "16言語対応",
      "searchPlaceholder": "電卓、変換ツールを検索...",
      "popular": "人気のツール:",
      "browseCategories": "カテゴリ別に探す",
      "browseCategoriesDesc": "便利に分類されたウェブユーティリティの幅広いライブラリをご覧ください。金融からウェブ開発まで、必要なものがすべて揃っています。",
      "mostPopularTools": "最も人気のあるツール",
      "mostPopularToolsDesc": "日々の計算や変換のニーズに対して、これらの高評価の無料オンラインツールに依存している何千人ものユーザーに加わりましょう。",
      "exploreAll": "すべて見る",
      "whyUse": "当プラットフォームを選ぶ理由",
      "whyUseDesc": "私たちは何よりもユーザー体験を優先しています。当プラットフォームは、デジタルプライバシーを損なうことなく即座に結果を提供するように設計されています。",
      "featureSpeedTitle": "超高速処理",
      "featureSpeedDesc": "すべての計算はブラウザ内でローカルに実行されます。ラグのない即時の変換を体験し、サーバーの応答を待つ必要はありません。",
      "featurePrivacyTitle": "厳格なプライバシー基準",
      "featurePrivacyDesc": "入力データは保存されません。あなたの情報は決してデバイスから離れることはなく、完全な機密性が確保されます。",
      "featureAccuracyTitle": "高精度の正確さ",
      "featureAccuracyDesc": "当社のアルゴリズムは標準化された公式を使用しています。税金の計算でも科学単位の変換でも、厳密な精度を期待できます。",
      "howItWorksTitle": "3つのステップで簡単操作",
      "howItWorksStep1": "ツールを見つける",
      "howItWorksStep1Desc": "スマート検索バーを使用するか、カテゴリを参照して、必要な特定の電卓またはコンバーターを見つけます。",
      "howItWorksStep2": "データを入力する",
      "howItWorksStep2Desc": "デスクトップとモバイルデバイスの両方のために設計された直感的なインターフェースに数値、テキスト、または日付を入力します。",
      "howItWorksStep3": "すぐに結果を取得",
      "howItWorksStep3Desc": "正確な結果をすぐに確認できます。ワンクリックでクリップボードにコピーしたり、エクスポートしたりできます。",
      "featuredTool": "今週のおすすめツール",
      "featuredToolDesc": "年齢電卓を試して、年、月、日、さらには秒単位の正確な年齢を完全に把握してください。",
      "featuredToolCTA": "年齢電卓を試す",
      "languagesTitle": "16言語で利用可能",
      "languagesDesc": "強力なユーティリティは誰もが利用できるべきだと考えています。母国語に切り替えて、シームレスな体験をお楽しみください。",
      "faqTitle": "よくある質問",
      "faq1Q": "これらのオンラインツールは完全に無料ですか？",
      "faq1A": "はい、その通りです。電卓、コンバーターなどのすべてのツールは100％無料です。隠れた料金やサブスクリプションはありません。",
      "faq2Q": "電卓を使用するためにアカウントを作成する必要がありますか？",
      "faq2A": "サインアップや登録は必要ありません。個人情報を提供することなく、ウェブサイトのすべての機能をすぐに利用できます。",
      "faq3Q": "私のデータはサーバーに保存されますか？",
      "faq3A": "いいえ。ほとんどのツールはウェブブラウザ内でローカルにデータを処理します。入力された数値を収集したり保存したりしません。",
      "faq4Q": "金融計算機の精度はどのくらいですか？",
      "faq4A": "標準的な会計公式を使用して構築されています。ただし、情報提供を目的としており、専門的なアドバイスに代わるものではありません。",
      "faq5Q": "スマートフォンでも利用できますか？",
      "faq5A": "はい、私たちのプラットフォームは完全にレスポンシブです。スマートフォン、タブレット、デスクトップで完璧に動作します。",
      "faq6Q": "新しいツールはどのくらいの頻度で追加されますか？",
      "faq6A": "ユーザーからのフィードバックに基づき、毎週新しい電卓やユーティリティを追加し、ディレクトリを継続的に拡張しています。",
      "ctaTitle": "タスクを簡素化する準備はできましたか？",
      "ctaDesc": "手動での計算に時間を無駄にするのはやめましょう。今すぐ無料のオンラインツールを使い始めて、生産性を高めましょう。",
      "ctaButton": "すべてのカテゴリを見る"
    }
  },
  "ko": {
    "Home": {
      "metaTitle": "무료 온라인 도구 및 계산기",
      "metaDescription": "무료 온라인 도구, 단위 변환기, 웹 유틸리티의 종합 모음에 액세스하세요. 가입 불필요. 빠르고 안전하며 정확합니다.",
      "heroH1": "모든 필요를 위한 무료 온라인 도구",
      "heroSub": "일상적인 작업을 간소화하기 위해 빠르고 안전하며 매우 정확한 무료 온라인 계산기 및 변환기 모음을 만나보세요.",
      "trustFree": "100% 무료",
      "trustNoSignup": "가입 불필요",
      "trustBrowser": "브라우저에서 실행",
      "trustLanguages": "16개 언어 지원",
      "searchPlaceholder": "계산기, 변환기 검색...",
      "popular": "인기 도구:",
      "browseCategories": "카테고리별로 찾아보기",
      "browseCategoriesDesc": "편의를 위해 카테고리화된 방대한 웹 유틸리티 라이브러리를 탐색하세요. 금융부터 웹 개발까지 모든 것을 찾을 수 있습니다.",
      "mostPopularTools": "가장 인기 있는 도구",
      "mostPopularToolsDesc": "일상적인 수학 및 변환 요구 사항에 대해 이 높은 평가를 받는 무료 온라인 도구를 사용하는 수천 명의 사용자와 함께하세요.",
      "exploreAll": "모두 보기",
      "whyUse": "왜 우리 플랫폼을 선택해야 할까요?",
      "whyUseDesc": "우리는 사용자 경험을 최우선으로 생각합니다. 우리 플랫폼은 디지털 개인 정보를 훼손하지 않으면서 즉각적인 결과를 제공합니다.",
      "featureSpeedTitle": "초고속 처리",
      "featureSpeedDesc": "모든 계산은 브라우저에서 로컬로 수행됩니다. 서버 응답을 기다릴 필요 없이 지연 없는 즉각적인 변환을 경험하세요.",
      "featurePrivacyTitle": "엄격한 개인 정보 보호",
      "featurePrivacyDesc": "우리는 귀하의 입력 데이터를 저장하지 않습니다. 귀하의 정보는 절대 기기를 벗어나지 않아 완벽한 기밀성을 보장합니다.",
      "featureAccuracyTitle": "높은 정밀도",
      "featureAccuracyDesc": "우리의 알고리즘은 전 세계적으로 허용되는 표준 공식을 사용합니다. 세금을 계산하든 과학 단위를 변환하든 엄격한 정밀도를 기대하세요.",
      "howItWorksTitle": "3단계로 쉽게 사용하기",
      "howItWorksStep1": "도구 찾기",
      "howItWorksStep1Desc": "스마트 검색 표시줄을 사용하거나 잘 정리된 카테고리를 찾아 필요한 특정 계산기 또는 변환기를 찾으세요.",
      "howItWorksStep2": "데이터 입력하기",
      "howItWorksStep2Desc": "데스크톱 및 모바일 기기 모두에 맞게 설계된 직관적이고 사용자 친화적인 인터페이스에 숫자, 텍스트 또는 날짜를 입력하세요.",
      "howItWorksStep3": "즉각적인 결과 얻기",
      "howItWorksStep3Desc": "정확한 결과를 즉시 확인하세요. 단 한 번의 클릭으로 클립보드에 복사하거나 개인 기록을 위해 내보낼 수 있습니다.",
      "featuredTool": "이번 주의 추천 도구",
      "featuredToolDesc": "연, 월, 일은 물론 초 단위까지 정확한 나이를 알아볼 수 있는 종합 나이 계산기를 사용해 보세요.",
      "featuredToolCTA": "나이 계산기 사용해 보기",
      "languagesTitle": "16개 언어로 제공",
      "languagesDesc": "우리는 모든 사람이 강력한 유틸리티에 접근할 수 있어야 한다고 믿습니다. 원활한 경험을 위해 모국어로 전환하세요.",
      "faqTitle": "자주 묻는 질문",
      "faq1Q": "이 온라인 도구들은 완전히 무료인가요?",
      "faq1A": "네, 그렇습니다. 계산기, 변환기 및 유틸리티의 전체 제품군은 100% 무료입니다. 숨겨진 수수료나 구독이 없습니다.",
      "faq2Q": "계산기를 사용하려면 계정을 만들어야 하나요?",
      "faq2A": "가입이나 등록이 필요하지 않습니다. 개인 정보를 제공하지 않고도 웹사이트의 모든 기능을 즉시 사용할 수 있습니다.",
      "faq3Q": "내 데이터가 서버에 저장되나요?",
      "faq3A": "아닙니다. 당사의 방대한 도구는 웹 브라우저 내에서 로컬로 데이터를 처리합니다. 우리는 귀하의 숫자를 수집하지 않습니다.",
      "faq4Q": "금융 계산기는 얼마나 정확한가요?",
      "faq4A": "우리의 금융 도구는 표준 회계 공식을 사용하여 작성되었습니다. 그러나 정보 제공 목적이며 전문적인 조언을 대체하지는 않습니다.",
      "faq5Q": "휴대전화에서 이 웹사이트를 사용할 수 있나요?",
      "faq5A": "예, 당사 플랫폼은 반응형 웹입니다. 스마트폰, 태블릿 및 데스크톱 컴퓨터에서 완벽하게 작동하도록 최적화되어 있습니다.",
      "faq6Q": "새로운 도구는 얼마나 자주 추가되나요?",
      "faq6A": "우리는 지속적으로 디렉토리를 확장합니다. 사용자 피드백을 기반으로 매주 새로운 계산기와 유틸리티가 추가됩니다.",
      "ctaTitle": "작업을 간소화할 준비가 되셨나요?",
      "ctaDesc": "수동으로 계산하는 데 시간을 낭비하지 마세요. 오늘부터 무료 온라인 도구를 사용하여 생산성을 높이세요.",
      "ctaButton": "모든 카테고리 보기"
    }
  }
};

import fs from 'fs';
for (const lang of Object.keys(content)) {
  const filePath = `messages/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data.Home = content[lang].Home;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}`);
  }
}
