const content = {
  "it": {
    "Home": {
      "metaTitle": "Strumenti Online Gratuiti e Calcolatrici",
      "metaDescription": "Accedi a una raccolta completa di strumenti online gratuiti, convertitori di unità e utilità web. Nessuna registrazione. Veloce, privato e preciso.",
      "heroH1": "Strumenti Online Gratuiti per Ogni Esigenza",
      "heroSub": "Scopri la nostra collezione di calcolatrici e convertitori online veloci, privati e precisi per semplificare le tue attività quotidiane.",
      "trustFree": "100% Gratuito",
      "trustNoSignup": "Nessuna Registrazione",
      "trustBrowser": "Eseguito nel Browser",
      "trustLanguages": "16 Lingue",
      "searchPlaceholder": "Cerca calcolatrici, convertitori...",
      "popular": "Popolare:",
      "browseCategories": "Sfoglia per Categoria",
      "browseCategoriesDesc": "Esplora la nostra vasta libreria di utilità web categorizzate. Dalla finanza allo sviluppo web, trova esattamente ciò di cui hai bisogno.",
      "mostPopularTools": "Strumenti Più Popolari",
      "mostPopularToolsDesc": "Unisciti a migliaia di utenti che si affidano a questi eccellenti strumenti online gratuiti per le loro esigenze quotidiane di calcolo e conversione.",
      "exploreAll": "Esplora Tutti",
      "whyUse": "Perché Scegliere la Nostra Piattaforma?",
      "whyUseDesc": "La nostra piattaforma è progettata per fornire risultati immediati senza compromettere la tua privacy digitale o la sicurezza dei dati.",
      "featureSpeedTitle": "Elaborazione Fulminea",
      "featureSpeedDesc": "Tutti i calcoli vengono eseguiti localmente nel tuo browser. Zero ritardi, conversioni istantanee e nessuna attesa per le risposte del server.",
      "featurePrivacyTitle": "Rigorosi Standard di Privacy",
      "featurePrivacyDesc": "Non memorizziamo i dati inseriti. Le tue informazioni non lasciano mai il tuo dispositivo, garantendo la totale riservatezza.",
      "featureAccuracyTitle": "Precisione ad Alta Fedeltà",
      "featureAccuracyDesc": "I nostri algoritmi utilizzano formule standardizzate. Che si tratti di calcolare le tasse o convertire unità scientifiche, aspettati una precisione rigorosa.",
      "howItWorksTitle": "Come Funziona in 3 Passaggi",
      "howItWorksStep1": "Trova il tuo strumento",
      "howItWorksStep1Desc": "Usa la barra di ricerca intelligente o naviga attraverso le nostre categorie per individuare il convertitore specifico di cui hai bisogno.",
      "howItWorksStep2": "Inserisci i tuoi dati",
      "howItWorksStep2Desc": "Inserisci numeri, testi o date nella nostra interfaccia intuitiva, progettata sia per dispositivi desktop che mobili.",
      "howItWorksStep3": "Ottieni risultati immediati",
      "howItWorksStep3Desc": "Visualizza i tuoi risultati all'istante. Copiali negli appunti con un clic o esportali per i tuoi archivi personali.",
      "featuredTool": "Strumento in Evidenza della Settimana",
      "featuredToolDesc": "Prova il nostro Calcolatore di Età per scoprire la tua età esatta in anni, mesi, giorni e persino secondi con assoluta precisione.",
      "featuredToolCTA": "Prova il Calcolatore di Età",
      "languagesTitle": "Disponibile in 16 Lingue",
      "languagesDesc": "Passa alla tua lingua madre per un'esperienza localizzata senza interruzioni. Utilità potenti accessibili a tutti.",
      "faqTitle": "Domande Frequenti",
      "faq1Q": "Questi strumenti online sono completamente gratuiti?",
      "faq1A": "Sì, assolutamente. L'intera suite di calcolatrici, convertitori e utilità per sviluppatori è gratuita al 100%. Nessun costo nascosto.",
      "faq2Q": "Devo creare un account per usare le calcolatrici?",
      "faq2A": "Non è richiesta alcuna registrazione. Puoi accedere a ogni funzionalità del nostro sito web immediatamente, senza fornire informazioni personali.",
      "faq3Q": "I miei dati sono memorizzati sui vostri server?",
      "faq3A": "No. La stragrande maggioranza dei nostri strumenti elabora i dati localmente nel tuo browser. Non raccogliamo né conserviamo i numeri o i testi inseriti.",
      "faq4Q": "Quanto sono precise le calcolatrici finanziarie?",
      "faq4A": "Utilizzano formule contabili standard e sono controllate regolarmente. Tuttavia, hanno scopo informativo e non sostituiscono una consulenza professionale.",
      "faq5Q": "Posso usare questo sito sul mio cellulare?",
      "faq5A": "Sì, la nostra piattaforma è completamente responsiva. È ottimizzata per funzionare perfettamente su smartphone, tablet e computer.",
      "faq6Q": "Ogni quanto vengono aggiunti nuovi strumenti?",
      "faq6A": "Espandiamo continuamente la nostra directory. Nuove calcolatrici e utilità vengono aggiunte ogni settimana in base al feedback degli utenti.",
      "ctaTitle": "Pronto a semplificare i tuoi compiti?",
      "ctaDesc": "Smetti di perdere tempo a fare calcoli manuali. Inizia a utilizzare i nostri strumenti online gratuiti oggi stesso.",
      "ctaButton": "Visualizza Tutte le Categorie"
    }
  },
  "pt": {
    "Home": {
      "metaTitle": "Ferramentas Online Grátis e Calculadoras",
      "metaDescription": "Acesse uma coleção completa de ferramentas online grátis, conversores de unidades e calculadoras. Sem necessidade de cadastro. Rápido, seguro e preciso.",
      "heroH1": "Ferramentas Online Grátis para Cada Necessidade",
      "heroSub": "Descubra nossa coleção de calculadoras e conversores online precisos, seguros e rápidos para simplificar suas tarefas diárias.",
      "trustFree": "100% Grátis",
      "trustNoSignup": "Sem Cadastro",
      "trustBrowser": "Roda no Navegador",
      "trustLanguages": "16 Idiomas",
      "searchPlaceholder": "Pesquisar calculadoras, conversores...",
      "popular": "Popular:",
      "browseCategories": "Navegar por Categoria",
      "browseCategoriesDesc": "Explore nossa vasta biblioteca de utilitários da web categorizados para sua conveniência. Encontre exatamente o que você precisa.",
      "mostPopularTools": "Ferramentas Mais Populares",
      "mostPopularToolsDesc": "Junte-se a milhares de usuários que confiam nestas ferramentas online gratuitas de alta qualidade para suas necessidades diárias.",
      "exploreAll": "Explorar Todas",
      "whyUse": "Por que Escolher Nossa Plataforma?",
      "whyUseDesc": "Priorizamos a experiência do usuário. Nossa plataforma foi projetada para entregar resultados instantâneos sem comprometer sua privacidade.",
      "featureSpeedTitle": "Processamento Ultrarrápido",
      "featureSpeedDesc": "Todos os cálculos são executados localmente no seu navegador. Experimente zero atraso e conversões instantâneas sem depender do servidor.",
      "featurePrivacyTitle": "Rigorosos Padrões de Privacidade",
      "featurePrivacyDesc": "Não armazenamos seus dados de entrada. Suas informações nunca saem do seu dispositivo, garantindo total confidencialidade.",
      "featureAccuracyTitle": "Alta Precisão",
      "featureAccuracyDesc": "Nossos algoritmos utilizam fórmulas padronizadas globalmente para garantir precisão rigorosa em cálculos fiscais ou científicos.",
      "howItWorksTitle": "Como Funciona em 3 Passos",
      "howItWorksStep1": "Encontre sua ferramenta",
      "howItWorksStep1Desc": "Use a barra de pesquisa inteligente ou navegue em nossas categorias organizadas para localizar a calculadora específica que você precisa.",
      "howItWorksStep2": "Insira seus dados",
      "howItWorksStep2Desc": "Coloque seus números ou textos em nossa interface intuitiva e fácil de usar, projetada para computadores e dispositivos móveis.",
      "howItWorksStep3": "Obtenha resultados instantâneos",
      "howItWorksStep3Desc": "Visualize seus resultados com precisão e instantaneamente. Copie-os para a área de transferência com um único clique.",
      "featuredTool": "Ferramenta em Destaque da Semana",
      "featuredToolDesc": "Experimente nossa abrangente Calculadora de Idade para descobrir sua idade exata em anos, meses, dias e até segundos.",
      "featuredToolCTA": "Testar Calculadora de Idade",
      "languagesTitle": "Disponível em 16 Idiomas",
      "languagesDesc": "Acreditamos que utilitários poderosos devem ser acessíveis a todos. Mude para o seu idioma nativo para uma experiência contínua.",
      "faqTitle": "Perguntas Frequentes",
      "faq1Q": "Essas ferramentas online são totalmente gratuitas?",
      "faq1A": "Sim, absolutamente. Toda a nossa gama de calculadoras, conversores e utilitários para desenvolvedores é 100% grátis. Não há taxas ocultas.",
      "faq2Q": "Preciso criar uma conta para usar as calculadoras?",
      "faq2A": "Nenhum cadastro ou registro é necessário. Você pode acessar e usar todos os recursos do nosso site imediatamente, sem informações pessoais.",
      "faq3Q": "Meus dados ficam armazenados nos seus servidores?",
      "faq3A": "Não. A grande maioria de nossas ferramentas processa os dados localmente no seu navegador. Não coletamos ou armazenamos seus números.",
      "faq4Q": "Quão precisas são as calculadoras financeiras?",
      "faq4A": "Nossas ferramentas financeiras usam fórmulas contábeis padrão e são auditadas regularmente, servindo apenas para fins informativos.",
      "faq5Q": "Posso usar este site no meu celular?",
      "faq5A": "Sim, nossa plataforma é totalmente responsiva. Ela é otimizada para funcionar perfeitamente em smartphones, tablets e computadores de mesa.",
      "faq6Q": "Com que frequência novas ferramentas são adicionadas?",
      "faq6A": "Expandimos continuamente nosso diretório. Novas calculadoras e utilitários são adicionados semanalmente com base no feedback dos usuários.",
      "ctaTitle": "Pronto para simplificar suas tarefas?",
      "ctaDesc": "Pare de perder tempo com cálculos manuais. Comece a usar nossas ferramentas online gratuitas hoje mesmo.",
      "ctaButton": "Ver Todas as Categorias"
    }
  },
  "nl": {
    "Home": {
      "metaTitle": "Gratis Online Tools & Rekenmachines",
      "metaDescription": "Krijg toegang tot een uitgebreide verzameling gratis online tools, eenhedenomzetters en ontwikkelaarstools. Geen registratie nodig. Snel, privé en nauwkeurig.",
      "heroH1": "Gratis Online Tools voor Elke Behoefte",
      "heroSub": "Ontdek onze verzameling van snelle, private en zeer nauwkeurige gratis online tools en rekenmachines om uw dagelijkse taken te vereenvoudigen.",
      "trustFree": "100% Gratis",
      "trustNoSignup": "Geen Registratie",
      "trustBrowser": "Werkt in Browser",
      "trustLanguages": "16 Talen",
      "searchPlaceholder": "Zoek rekenmachines, omzetters...",
      "popular": "Populair:",
      "browseCategories": "Blader op Categorie",
      "browseCategoriesDesc": "Verken onze uitgebreide bibliotheek met webhulpprogramma's, handig gecategoriseerd. Van financiën tot webontwikkeling, vind precies wat u nodig heeft.",
      "mostPopularTools": "Meest Populaire Tools",
      "mostPopularToolsDesc": "Sluit u aan bij duizenden gebruikers die vertrouwen op deze hoogwaardige gratis online tools voor hun dagelijkse berekenings- en conversiebehoeften.",
      "exploreAll": "Bekijk Alles",
      "whyUse": "Waarom Kiezen Voor Ons Platform?",
      "whyUseDesc": "Wij geven prioriteit aan de gebruikerservaring. Ons platform is gebouwd om direct resultaten te leveren zonder in te leveren op uw digitale privacy.",
      "featureSpeedTitle": "Bliksemsnelle Verwerking",
      "featureSpeedDesc": "Alle berekeningen worden lokaal in uw browser uitgevoerd. Ervaar geen vertragingen en directe conversies zonder te wachten op servers.",
      "featurePrivacyTitle": "Strikte Privacynormen",
      "featurePrivacyDesc": "We slaan uw ingevoerde gegevens niet op. Uw informatie verlaat uw apparaat nooit, waardoor volledige vertrouwelijkheid wordt gegarandeerd.",
      "featureAccuracyTitle": "Zeer Hoge Nauwkeurigheid",
      "featureAccuracyDesc": "Onze algoritmen gebruiken gestandaardiseerde, wereldwijd geaccepteerde formules voor een altijd rigoureuze nauwkeurigheid.",
      "howItWorksTitle": "Hoe Het Werkt in 3 Stappen",
      "howItWorksStep1": "Vind uw tool",
      "howItWorksStep1Desc": "Gebruik de slimme zoekbalk of blader door onze overzichtelijke categorieën om de specifieke rekenmachine of omzetter te vinden.",
      "howItWorksStep2": "Voer uw gegevens in",
      "howItWorksStep2Desc": "Voer uw getallen, tekst of datums in onze intuïtieve en gebruiksvriendelijke interface in, ontworpen voor desktop en mobiel.",
      "howItWorksStep3": "Krijg direct resultaat",
      "howItWorksStep3Desc": "Bekijk uw nauwkeurige resultaten onmiddellijk. Kopieer ze met één klik naar uw klembord of exporteer ze.",
      "featuredTool": "Uitgelichte Tool van de Week",
      "featuredToolDesc": "Probeer onze uitgebreide Leeftijdscalculator om uw exacte leeftijd in jaren, maanden, dagen en zelfs seconden met precisie te bepalen.",
      "featuredToolCTA": "Probeer Leeftijdscalculator",
      "languagesTitle": "Beschikbaar in 16 Talen",
      "languagesDesc": "Wij vinden dat krachtige tools voor iedereen toegankelijk moeten zijn. Schakel over naar uw moedertaal voor de beste ervaring.",
      "faqTitle": "Veelgestelde Vragen",
      "faq1Q": "Zijn deze online tools volledig gratis te gebruiken?",
      "faq1A": "Ja, absoluut. Onze hele reeks rekenmachines, omzetters en ontwikkelaarstools is 100% gratis. Er zijn geen verborgen kosten.",
      "faq2Q": "Moet ik een account aanmaken om de rekenmachines te gebruiken?",
      "faq2A": "Aanmelden is niet vereist. U kunt elke functie op onze website direct gebruiken, zonder persoonlijke informatie te hoeven verstrekken.",
      "faq3Q": "Worden mijn gegevens opgeslagen op uw servers?",
      "faq3A": "Nee. De overgrote meerderheid van onze tools verwerkt gegevens lokaal in uw webbrowser. Wij slaan uw ingevoerde getallen of tekst niet op.",
      "faq4Q": "Hoe nauwkeurig zijn de financiële rekenmachines?",
      "faq4A": "Onze financiële tools zijn gebouwd met behulp van standaard boekhoudformules. Ze zijn voor informatieve doeleinden en vervangen geen professioneel advies.",
      "faq5Q": "Kan ik deze website op mijn mobiele telefoon gebruiken?",
      "faq5A": "Ja, ons platform is volledig responsief en geoptimaliseerd om perfect te werken op smartphones, tablets en desktopcomputers.",
      "faq6Q": "Hoe vaak worden er nieuwe tools toegevoegd?",
      "faq6A": "We breiden onze database wekelijks uit met nieuwe rekenmachines en handige webhulpprogramma's op basis van feedback van gebruikers.",
      "ctaTitle": "Klaar om uw taken te vereenvoudigen?",
      "ctaDesc": "Verspil geen tijd meer aan handmatige berekeningen. Gebruik vandaag nog onze gratis online tools en verhoog uw productiviteit.",
      "ctaButton": "Bekijk Alle Categorieën"
    }
  },
  "pl": {
    "Home": {
      "metaTitle": "Darmowe Narzędzia Online i Kalkulatory",
      "metaDescription": "Uzyskaj dostęp do kompleksowej kolekcji darmowych narzędzi online, przeliczników jednostek i narzędzi dla programistów. Bez logowania. Szybko, prywatnie i dokładnie.",
      "heroH1": "Darmowe Narzędzia Online na Każdą Potrzebę",
      "heroSub": "Odkryj naszą kolekcję szybkich, prywatnych i niezwykle precyzyjnych darmowych kalkulatorów i przeliczników online, które uproszczą Twoje codzienne zadania.",
      "trustFree": "100% Darmowe",
      "trustNoSignup": "Bez Logowania",
      "trustBrowser": "Działa w Przeglądarce",
      "trustLanguages": "16 Języków",
      "searchPlaceholder": "Szukaj kalkulatorów, przeliczników...",
      "popular": "Popularne:",
      "browseCategories": "Przeglądaj Kategorie",
      "browseCategoriesDesc": "Zbadaj naszą rozbudowaną bibliotekę narzędzi internetowych posegregowaną w kategorie. Od finansów po tworzenie stron WWW, znajdź to, czego szukasz.",
      "mostPopularTools": "Najpopularniejsze Narzędzia",
      "mostPopularToolsDesc": "Dołącz do tysięcy użytkowników, którzy na co dzień polegają na tych wysoko ocenianych darmowych narzędziach online.",
      "exploreAll": "Zobacz Wszystkie",
      "whyUse": "Dlaczego Warto Wybrać Naszą Platformę?",
      "whyUseDesc": "Stawiamy przede wszystkim na doświadczenie użytkownika. Nasza platforma ma za zadanie dostarczać natychmiastowe wyniki bez naruszania prywatności.",
      "featureSpeedTitle": "Błyskawiczne Przetwarzanie",
      "featureSpeedDesc": "Wszystkie obliczenia wykonywane są lokalnie w Twojej przeglądarce. Doświadcz braku opóźnień i natychmiastowych przeliczeń bez czekania na serwer.",
      "featurePrivacyTitle": "Surowe Standardy Prywatności",
      "featurePrivacyDesc": "Nie przechowujemy wprowadzanych danych. Twoje informacje nigdy nie opuszczają urządzenia, co zapewnia całkowitą poufność.",
      "featureAccuracyTitle": "Wysoka Precyzja",
      "featureAccuracyDesc": "Nasze algorytmy korzystają ze standardowych, powszechnie uznanych wzorów matematycznych, zapewniając rygorystyczną precyzję w każdych obliczeniach.",
      "howItWorksTitle": "Jak to Działa w 3 Krokach",
      "howItWorksStep1": "Znajdź narzędzie",
      "howItWorksStep1Desc": "Skorzystaj z naszej inteligentnej wyszukiwarki lub przeglądaj odpowiednio zorganizowane kategorie, aby odnaleźć potrzebny Ci kalkulator.",
      "howItWorksStep2": "Wprowadź dane",
      "howItWorksStep2Desc": "Wprowadź swoje liczby, tekst lub daty w naszym intuicyjnym interfejsie zaprojektowanym specjalnie z myślą o komputerach i urządzeniach mobilnych.",
      "howItWorksStep3": "Otrzymaj natychmiastowy wynik",
      "howItWorksStep3Desc": "Zaraz po wprowadzeniu danych otrzymasz dokładny wynik, który możesz błyskawicznie skopiować do schowka zaledwie jednym kliknięciem.",
      "featuredTool": "Polecane Narzędzie Tygodnia",
      "featuredToolDesc": "Wypróbuj nasz kompleksowy Kalkulator Wieku, aby poznać swój dokładny wiek w latach, miesiącach, dniach, a nawet sekundach.",
      "featuredToolCTA": "Wypróbuj Kalkulator Wieku",
      "languagesTitle": "Dostępne w 16 Językach",
      "languagesDesc": "Wierzymy, że potężne narzędzia powinny być dostępne dla każdego. Przełącz się na swój język ojczysty, by korzystać z witryny w pełni komfortowo.",
      "faqTitle": "Często Zadawane Pytania",
      "faq1Q": "Czy te narzędzia internetowe są całkowicie darmowe?",
      "faq1A": "Tak, jak najbardziej. Nasz cały zestaw kalkulatorów, przeliczników oraz narzędzi dla programistów jest darmowy. Nie ma tu żadnych ukrytych opłat.",
      "faq2Q": "Czy muszę zakładać konto, żeby móc korzystać z tych narzędzi?",
      "faq2A": "Nie wymagamy żadnego logowania czy rejestracji. Umożliwiamy natychmiastowy dostęp do wszystkich narzędzi bez konieczności podawania danych osobowych.",
      "faq3Q": "Czy moje dane są gdzieś zapisywane lub wysyłane?",
      "faq3A": "Nie. Ogromna większość naszych narzędzi przetwarza informacje lokalnie, wprost w Twojej przeglądarce. Nikomu nie wysyłamy wpisanych wartości.",
      "faq4Q": "Jak precyzyjne są kalkulatory finansowe?",
      "faq4A": "Zostały one przygotowane na bazie uznanych standardów rachunkowości, ale mają one za zadanie tylko informować i nie mogą zastąpić profesjonalnej opinii eksperta.",
      "faq5Q": "Czy mogę korzystać z tej strony w swoim telefonie komórkowym?",
      "faq5A": "Zdecydowanie. Cała nasza platforma jest responsywna, by bezproblemowo funkcjonować na małych i dużych ekranach wszelkiego formatu.",
      "faq6Q": "Czy często będą dodawane kolejne, nowe opcje i kalkulatory?",
      "faq6A": "Staramy się powiększać nasze portfolio regularnie każdego tygodnia w odpowiedzi na cenne sugestie otrzymane prosto od naszej dużej bazy użytkowników.",
      "ctaTitle": "Gotowy, aby uprościć swoje zadania?",
      "ctaDesc": "Nie marnuj cennego czasu na obliczenia robione ręcznie. Rozpocznij korzystanie z naszych darmowych narzędzi online już dziś i zwiększ swoją wydajność.",
      "ctaButton": "Zbadaj Wszystkie Kategorie"
    }
  }
};

import fs from 'fs';
for (const lang of Object.keys(content)) {
  const filePath = `messages/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data.Home = content[lang].Home;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}`);
  }
}
