const content = {
  "ru": {
    "Home": {
      "metaTitle": "Бесплатные Онлайн Инструменты и Калькуляторы",
      "metaDescription": "Получите доступ к полной коллекции бесплатных онлайн-инструментов, конвертеров и утилит. Без регистрации. Быстро, конфиденциально и точно.",
      "heroH1": "Бесплатные Онлайн Инструменты для Любых Задач",
      "heroSub": "Откройте для себя нашу коллекцию быстрых, безопасных и невероятно точных онлайн-калькуляторов и конвертеров для упрощения ваших повседневных задач.",
      "trustFree": "100% Бесплатно",
      "trustNoSignup": "Без Регистрации",
      "trustBrowser": "Работает в Браузере",
      "trustLanguages": "16 Языков",
      "searchPlaceholder": "Поиск калькуляторов, конвертеров...",
      "popular": "Популярное:",
      "browseCategories": "Обзор по Категориям",
      "browseCategoriesDesc": "Изучите нашу обширную библиотеку веб-утилит, распределенных по категориям для вашего удобства. От финансов до веб-разработки.",
      "mostPopularTools": "Самые Популярные Инструменты",
      "mostPopularToolsDesc": "Присоединяйтесь к тысячам пользователей, которые ежедневно полагаются на эти высоко оцененные бесплатные онлайн-инструменты.",
      "exploreAll": "Смотреть Все",
      "whyUse": "Почему Стоит Выбрать Нашу Платформу?",
      "whyUseDesc": "Мы ставим пользовательский опыт превыше всего. Наша платформа создана для предоставления мгновенных результатов без ущерба для вашей цифровой конфиденциальности.",
      "featureSpeedTitle": "Молниеносная Обработка",
      "featureSpeedDesc": "Все вычисления выполняются локально в вашем браузере. Ощутите отсутствие задержек и мгновенную конвертацию без ожидания ответов от сервера.",
      "featurePrivacyTitle": "Строгие Стандарты Конфиденциальности",
      "featurePrivacyDesc": "Мы не храним ваши вводимые данные. Ваша информация никогда не покидает ваше устройство, что обеспечивает полную конфиденциальность.",
      "featureAccuracyTitle": "Высочайшая Точность",
      "featureAccuracyDesc": "Наши алгоритмы используют стандартизированные, общепринятые формулы. Ожидайте строгую точность при любых вычислениях.",
      "howItWorksTitle": "Как это Работает за 3 Шага",
      "howItWorksStep1": "Найдите нужный инструмент",
      "howItWorksStep1Desc": "Используйте умную панель поиска или просмотрите наши организованные категории, чтобы найти конкретный калькулятор.",
      "howItWorksStep2": "Введите ваши данные",
      "howItWorksStep2Desc": "Вводите числа, текст или даты в наш интуитивно понятный интерфейс, разработанный как для настольных, так и для мобильных устройств.",
      "howItWorksStep3": "Мгновенно получите результат",
      "howItWorksStep3Desc": "Точные результаты отображаются моментально. Скопируйте их в буфер обмена одним щелчком мыши или экспортируйте для себя.",
      "featuredTool": "Инструмент Недели",
      "featuredToolDesc": "Опробуйте наш Калькулятор Возраста, чтобы узнать свой точный возраст в годах, месяцах, днях и даже секундах с абсолютной точностью.",
      "featuredToolCTA": "Попробовать Калькулятор Возраста",
      "languagesTitle": "Доступно на 16 Языках",
      "languagesDesc": "Мы верим, что мощные утилиты должны быть доступны всем. Переключитесь на свой родной язык для максимального комфорта.",
      "faqTitle": "Часто Задаваемые Вопросы",
      "faq1Q": "Являются ли эти онлайн-инструменты полностью бесплатными?",
      "faq1A": "Да, абсолютно. Весь наш набор калькуляторов, конвертеров и утилит для разработчиков на 100% бесплатен. Скрытых платежей нет.",
      "faq2Q": "Нужно ли мне создавать учетную запись?",
      "faq2A": "Регистрация не требуется. Вы можете получить доступ ко всем функциям нашего сайта мгновенно, не предоставляя личную информацию.",
      "faq3Q": "Хранятся ли мои данные на ваших серверах?",
      "faq3A": "Нет. Подавляющее большинство наших инструментов обрабатывают данные локально в вашем браузере. Мы не собираем и не храним ваши цифры.",
      "faq4Q": "Насколько точны финансовые калькуляторы?",
      "faq4A": "Наши финансовые инструменты созданы с использованием стандартных бухгалтерских формул. Однако они не заменяют профессиональные финансовые консультации.",
      "faq5Q": "Могу ли я использовать этот сайт на своем мобильном телефоне?",
      "faq5A": "Да, наша платформа полностью адаптивна и оптимизирована для безупречной работы на смартфонах, планшетах и настольных компьютерах.",
      "faq6Q": "Как часто добавляются новые инструменты?",
      "faq6A": "Мы постоянно расширяем наш каталог. Новые калькуляторы и утилиты добавляются еженедельно на основе отзывов пользователей.",
      "ctaTitle": "Готовы упростить свои задачи?",
      "ctaDesc": "Хватит тратить время на ручные вычисления. Начните использовать наши бесплатные онлайн-инструменты уже сегодня и повысьте свою продуктивность.",
      "ctaButton": "Посмотреть Все Категории"
    }
  },
  "tr": {
    "Home": {
      "metaTitle": "Ücretsiz Çevrimiçi Araçlar ve Hesap Makineleri",
      "metaDescription": "Ücretsiz çevrimiçi araçlar, birim dönüştürücüler ve web yardımcı programlarından oluşan kapsamlı bir koleksiyona erişin. Kayıt yok. Hızlı, gizli ve doğru.",
      "heroH1": "Her İhtiyaç İçin Ücretsiz Çevrimiçi Araçlar",
      "heroSub": "Günlük görevlerinizi basitleştirmek için hızlı, gizliliğe önem veren ve son derece hassas çevrimiçi hesap makineleri koleksiyonumuzu keşfedin.",
      "trustFree": "%100 Ücretsiz",
      "trustNoSignup": "Kayıt Olmak Yok",
      "trustBrowser": "Tarayıcıda Çalışır",
      "trustLanguages": "16 Dil",
      "searchPlaceholder": "Hesap makinesi veya dönüştürücü ara...",
      "popular": "Popüler:",
      "browseCategories": "Kategorilere Göre Göz Atın",
      "browseCategoriesDesc": "Size kolaylık sağlamak için kategorize edilmiş geniş web araçları kütüphanemizi keşfedin. Finanstan web geliştirmeye kadar her şeyi bulun.",
      "mostPopularTools": "En Popüler Araçlar",
      "mostPopularToolsDesc": "Günlük matematiksel ve dönüştürme ihtiyaçları için bu yüksek puanlı ücretsiz çevrimiçi araçlara güvenen binlerce kullanıcıya katılın.",
      "exploreAll": "Tümünü Keşfet",
      "whyUse": "Neden Platformumuzu Seçmelisiniz?",
      "whyUseDesc": "Kullanıcı deneyimine her şeyden çok önem veriyoruz. Platformumuz dijital gizliliğinizden ödün vermeden anında sonuç sağlamak üzere tasarlanmıştır.",
      "featureSpeedTitle": "Işık Hızında İşlem",
      "featureSpeedDesc": "Tüm hesaplamalar yerel olarak tarayıcınızda gerçekleştirilir. Gecikme yaşamazsınız, anında dönüşüm yapabilirsiniz.",
      "featurePrivacyTitle": "Sıkı Gizlilik Standartları",
      "featurePrivacyDesc": "Girdiğiniz verileri asla saklamıyoruz. Bilgileriniz cihazınızdan asla ayrılmaz, böylece hesaplamalarınızın gizliliği tam olarak sağlanır.",
      "featureAccuracyTitle": "Yüksek Hassasiyet",
      "featureAccuracyDesc": "Algoritmalarımız küresel olarak kabul görmüş standart formüller kullanır. Kesin doğruluk bekleyebilirsiniz.",
      "howItWorksTitle": "3 Adımda Nasıl Çalışır",
      "howItWorksStep1": "Aracınızı bulun",
      "howItWorksStep1Desc": "İhtiyacınız olan hesap makinesini bulmak için akıllı arama çubuğunu kullanın veya kategorilerimize göz atın.",
      "howItWorksStep2": "Verilerinizi girin",
      "howItWorksStep2Desc": "Sayılarınızı veya metinlerinizi hem masaüstü hem de mobil cihazlar için tasarlanmış kullanımı kolay arayüzümüze girin.",
      "howItWorksStep3": "Anında sonuç alın",
      "howItWorksStep3Desc": "Doğru sonuçlarınızı anında görüntüleyin. Tek bir tıklamayla panonuza kopyalayabilir veya kaydedebilirsiniz.",
      "featuredTool": "Haftanın Öne Çıkan Aracı",
      "featuredToolDesc": "Tam yaşınızı yıl, ay, gün ve hatta saniye cinsinden mutlak doğrulukla bulmak için kapsamlı Yaş Hesaplayıcımızı deneyin.",
      "featuredToolCTA": "Yaş Hesaplayıcısını Dene",
      "languagesTitle": "16 Dilde Mevcut",
      "languagesDesc": "Güçlü araçların herkes için erişilebilir olması gerektiğine inanıyoruz. Sorunsuz bir deneyim için anadilinize geçin.",
      "faqTitle": "Sıkça Sorulan Sorular",
      "faq1Q": "Bu çevrimiçi araçları kullanmak tamamen ücretsiz mi?",
      "faq1A": "Evet, kesinlikle. Araçlarımızın tamamı %100 ücretsizdir. Gizli ücretler veya abonelikler yoktur.",
      "faq2Q": "Hesap makinelerini kullanmak için hesap oluşturmam gerekiyor mu?",
      "faq2A": "Hayır. Herhangi bir kayıt veya kişisel bilgi sağlamadan sitemizdeki tüm özellikleri anında kullanabilirsiniz.",
      "faq3Q": "Verilerim sunucularınızda saklanıyor mu?",
      "faq3A": "Hayır. Araçlarımızın büyük çoğunluğu verileri yerel olarak tarayıcınızda işler. Girdiğiniz rakamları toplamıyoruz.",
      "faq4Q": "Finansal hesap makineleri ne kadar doğru?",
      "faq4A": "Standart formüller kullanılarak oluşturulmuştur ancak yalnızca bilgi amaçlıdır ve profesyonel tavsiyenin yerini alamaz.",
      "faq5Q": "Bu web sitesini cep telefonumda kullanabilir miyim?",
      "faq5A": "Evet, platformumuz tamamen duyarlıdır. Akıllı telefonlarda ve tabletlerde mükemmel şekilde çalışacak şekilde optimize edilmiştir.",
      "faq6Q": "Ne sıklıkla yeni araçlar ekleniyor?",
      "faq6A": "Kataloğumuzu sürekli genişletiyoruz. Kullanıcı geri bildirimlerine dayalı olarak her hafta yeni hesap makineleri eklenmektedir.",
      "ctaTitle": "Görevlerinizi basitleştirmeye hazır mısınız?",
      "ctaDesc": "Manuel hesaplamalarla zaman kaybetmeyi bırakın. Ücretsiz çevrimiçi araçlarımızı bugün kullanmaya başlayın ve üretkenliğinizi artırın.",
      "ctaButton": "Tüm Kategorileri Görüntüle"
    }
  },
  "ar": {
    "Home": {
      "metaTitle": "أدوات مجانية عبر الإنترنت وحاسبات",
      "metaDescription": "الوصول إلى مجموعة شاملة من الأدوات المجانية عبر الإنترنت ومحولات الوحدات. لا حاجة للتسجيل. سريع، خاص، ودقيق للغاية.",
      "heroH1": "أدوات مجانية عبر الإنترنت لكل احتياجاتك",
      "heroSub": "اكتشف مجموعتنا من الحاسبات ومحولات الوحدات السريعة والدقيقة المصممة لتبسيط مهامك اليومية مع الحفاظ على خصوصيتك.",
      "trustFree": "مجاني 100%",
      "trustNoSignup": "بدون تسجيل",
      "trustBrowser": "يعمل في المتصفح",
      "trustLanguages": "16 لغة",
      "searchPlaceholder": "ابحث عن حاسبات، محولات...",
      "popular": "شائع:",
      "browseCategories": "تصفح حسب الفئة",
      "browseCategoriesDesc": "استكشف مكتبتنا الواسعة من أدوات الويب المصنفة لراحتك. من الشؤون المالية إلى تطوير الويب، اعثر على ما تحتاجه بالضبط.",
      "mostPopularTools": "الأدوات الأكثر شعبية",
      "mostPopularToolsDesc": "انضم إلى آلاف المستخدمين الذين يعتمدون على هذه الأدوات المجانية عالية التقييم لتلبية احتياجاتهم اليومية في الحساب والتحويل.",
      "exploreAll": "استكشف الجميع",
      "whyUse": "لماذا تختار منصتنا؟",
      "whyUseDesc": "نحن نضع تجربة المستخدم فوق كل اعتبار. تم تصميم منصتنا لتقديم نتائج فورية دون المساومة على خصوصيتك الرقمية.",
      "featureSpeedTitle": "معالجة فائقة السرعة",
      "featureSpeedDesc": "تتم جميع الحسابات محليًا في متصفحك. استمتع بانعدام التأخير، والتحويلات الفورية، وعدم الانتظار لاستجابات الخادم.",
      "featurePrivacyTitle": "معايير خصوصية صارمة",
      "featurePrivacyDesc": "نحن لا نقوم بتخزين بيانات الإدخال الخاصة بك. معلوماتك لا تغادر جهازك أبداً، مما يضمن السرية التامة لحساباتك.",
      "featureAccuracyTitle": "دقة عالية الدقة",
      "featureAccuracyDesc": "تستخدم خوارزمياتنا صيغاً قياسية مقبولة عالمياً. سواء كنت تحسب الضرائب أو تحول الوحدات العلمية، توقع دقة صارمة.",
      "howItWorksTitle": "كيف تعمل في 3 خطوات",
      "howItWorksStep1": "ابحث عن أداتك",
      "howItWorksStep1Desc": "استخدم شريط البحث الذكي الخاص بنا أو تصفح فئاتنا المنظمة للعثور على الحاسبة أو المحول الذي تحتاجه بالضبط.",
      "howItWorksStep2": "أدخل بياناتك",
      "howItWorksStep2Desc": "أدخل الأرقام أو النصوص أو التواريخ في واجهتنا البديهية المصممة لكل من أجهزة الكمبيوتر المكتبية والمحمولة.",
      "howItWorksStep3": "احصل على نتائج فورية",
      "howItWorksStep3Desc": "شاهد نتائجك الدقيقة على الفور. قم بنسخها إلى الحافظة بنقرة واحدة أو تصديرها لسجلاتك الشخصية.",
      "featuredTool": "الأداة المميزة لهذا الأسبوع",
      "featuredToolDesc": "جرب حاسبة العمر الشاملة لدينا لمعرفة عمرك الدقيق بالسنوات والأشهر والأيام وحتى الثواني بدقة مطلقة.",
      "featuredToolCTA": "جرب حاسبة العمر",
      "languagesTitle": "متوفر بـ 16 لغة",
      "languagesDesc": "نحن نؤمن بأنه يجب أن تكون الأدوات القوية متاحة للجميع. قم بالتبديل إلى لغتك الأم للحصول على تجربة محلية سلسة.",
      "faqTitle": "الأسئلة الشائعة",
      "faq1Q": "هل استخدام هذه الأدوات عبر الإنترنت مجاني بالكامل؟",
      "faq1A": "نعم، بالتأكيد. مجموعتنا الكاملة من الحاسبات والمحولات مجانية 100%. لا توجد رسوم خفية أو اشتراكات مطلوبة.",
      "faq2Q": "هل أحتاج إلى إنشاء حساب لاستخدام الحاسبات؟",
      "faq2A": "لا يلزم التسجيل أو إنشاء حساب. يمكنك الوصول إلى جميع الميزات واستخدامها على الفور دون تقديم أي معلومات شخصية.",
      "faq3Q": "هل يتم تخزين بياناتي على خوادمكم؟",
      "faq3A": "لا. تقوم الغالبية العظمى من أدواتنا بمعالجة البيانات محليًا داخل متصفح الويب الخاص بك. نحن لا نجمع بياناتك.",
      "faq4Q": "ما مدى دقة الحاسبات المالية؟",
      "faq4A": "تم بناء أدواتنا باستخدام صيغ محاسبية قياسية. ومع ذلك، فهي للأغراض المعلوماتية ولا يجب أن تحل محل المشورة المهنية.",
      "faq5Q": "هل يمكنني استخدام هذا الموقع على هاتفي المحمول؟",
      "faq5A": "نعم، منصتنا متجاوبة تمامًا وتم تحسينها لتعمل بشكل مثالي على الهواتف الذكية والأجهزة اللوحية وأجهزة الكمبيوتر.",
      "faq6Q": "كم مرة تتم إضافة أدوات جديدة؟",
      "faq6A": "نحن نقوم بتوسيع دليلنا باستمرار. تتم إضافة أدوات وحاسبات جديدة أسبوعياً بناءً على ملاحظات المستخدمين.",
      "ctaTitle": "هل أنت مستعد لتبسيط مهامك؟",
      "ctaDesc": "توقف عن إضاعة الوقت في الحسابات اليدوية. ابدأ في استخدام أدواتنا المجانية عبر الإنترنت اليوم.",
      "ctaButton": "عرض جميع الفئات"
    }
  },
  "bn": {
    "Home": {
      "metaTitle": "ফ্রি অনলাইন টুলস এবং ক্যালকুলেটর",
      "metaDescription": "ফ্রি অনলাইন টুলস, ইউনিট কনভার্টার এবং ওয়েব ইউটিলিটির একটি বিস্তৃত সংগ্রহ ব্যবহার করুন। কোন সাইনআপের প্রয়োজন নেই। দ্রুত, নিরাপদ এবং সঠিক।",
      "heroH1": "প্রতিটি প্রয়োজনের জন্য ফ্রি অনলাইন টুলস",
      "heroSub": "আপনার দৈনন্দিন কাজগুলোকে সহজ করতে আমাদের দ্রুত, প্রাইভেট এবং অত্যন্ত সঠিক অনলাইন ক্যালকুলেটর এবং কনভার্টারগুলোর সংগ্রহ আবিষ্কার করুন।",
      "trustFree": "১০০% ফ্রি",
      "trustNoSignup": "কোনো সাইনআপ নেই",
      "trustBrowser": "ব্রাউজারেই চলে",
      "trustLanguages": "১৬টি ভাষা",
      "searchPlaceholder": "ক্যালকুলেটর, কনভার্টার খুঁজুন...",
      "popular": "জনপ্রিয়:",
      "browseCategories": "ক্যাটাগরি অনুযায়ী ব্রাউজ করুন",
      "browseCategoriesDesc": "আপনার সুবিধার জন্য ক্যাটাগরি অনুযায়ী আমাদের ওয়েব ইউটিলিটিগুলোর বিস্তৃত লাইব্রেরি ঘুরে দেখুন। ফাইন্যান্স থেকে ওয়েব ডেভেলপমেন্ট পর্যন্ত সব আছে।",
      "mostPopularTools": "সবচেয়ে জনপ্রিয় টুলস",
      "mostPopularToolsDesc": "হাজার হাজার ব্যবহারকারীর সাথে যোগ দিন যারা তাদের দৈনন্দিন গাণিতিক এবং কনভার্সনের প্রয়োজনের জন্য এই উচ্চ-রেটেড ফ্রি অনলাইন টুলসগুলোর ওপর নির্ভর করে।",
      "exploreAll": "সবগুলো এক্সপ্লোর করুন",
      "whyUse": "আমাদের প্ল্যাটফর্ম কেন বেছে নেবেন?",
      "whyUseDesc": "আমরা ব্যবহারকারীর অভিজ্ঞতাকে সবকিছুর উর্ধ্বে রাখি। আপনার ডিজিটাল গোপনীয়তা বা ডেটা নিরাপত্তার সাথে আপস না করে তাৎক্ষণিক ফলাফল প্রদানের জন্য আমাদের প্ল্যাটফর্ম তৈরি করা হয়েছে।",
      "featureSpeedTitle": "বিদ্যুৎ গতির প্রসেসিং",
      "featureSpeedDesc": "সমস্ত গণনা স্থানীয়ভাবে আপনার ব্রাউজারে সঞ্চালিত হয়। কোনো ল্যাগ নেই, তাৎক্ষণিক কনভার্সন এবং সার্ভারের প্রতিক্রিয়ার জন্য কোনো অপেক্ষার প্রয়োজন নেই।",
      "featurePrivacyTitle": "কঠোর গোপনীয়তা মান",
      "featurePrivacyDesc": "আমরা আপনার ইনপুট করা ডেটা সংরক্ষণ করি না। আপনার তথ্য কখনোই আপনার ডিভাইস থেকে বের হয় না, যা সম্পূর্ণ গোপনীয়তা নিশ্চিত করে।",
      "featureAccuracyTitle": "উচ্চ নির্ভুলতা",
      "featureAccuracyDesc": "আমাদের অ্যালগরিদমগুলো মানসম্মত, বিশ্বব্যাপী স্বীকৃত সূত্র ব্যবহার করে। কর গণনা করা হোক বা বৈজ্ঞানিক ইউনিট রূপান্তর করা হোক, কঠোর নির্ভুলতা আশা করুন।",
      "howItWorksTitle": "৩টি ধাপে যেভাবে কাজ করে",
      "howItWorksStep1": "আপনার টুল খুঁজুন",
      "howItWorksStep1Desc": "আপনার প্রয়োজনীয় নির্দিষ্ট ক্যালকুলেটর বা কনভার্টার খুঁজে পেতে আমাদের স্মার্ট সার্চ বার ব্যবহার করুন বা ক্যাটাগরিগুলো ব্রাউজ করুন।",
      "howItWorksStep2": "আপনার ডেটা ইনপুট করুন",
      "howItWorksStep2Desc": "ডেস্কটপ এবং মোবাইল ডিভাইস উভয়ের জন্যই ডিজাইন করা আমাদের সহজ ইন্টারফেসে আপনার সংখ্যা, টেক্সট বা তারিখগুলো ইনপুট করুন।",
      "howItWorksStep3": "তাৎক্ষণিক ফলাফল পান",
      "howItWorksStep3Desc": "আপনার সঠিক ফলাফলগুলো তাৎক্ষণিকভাবে দেখুন। এক ক্লিকে সেগুলোকে আপনার ক্লিপবোর্ডে কপি করুন বা এক্সপোর্ট করুন।",
      "featuredTool": "সপ্তাহের সেরা টুল",
      "featuredToolDesc": "আপনার সঠিক বয়স বছর, মাস, দিন এবং এমনকি সেকেন্ডে নির্ভুলভাবে জানতে আমাদের ব্যাপক বয়স ক্যালকুলেটরটি ব্যবহার করে দেখুন।",
      "featuredToolCTA": "বয়স ক্যালকুলেটর ট্রাই করুন",
      "languagesTitle": "১৬টি ভাষায় উপলব্ধ",
      "languagesDesc": "আমরা বিশ্বাস করি শক্তিশালী ইউটিলিটিগুলো সবার জন্য অ্যাক্সেসযোগ্য হওয়া উচিত। একটি নিরবচ্ছিন্ন অভিজ্ঞতার জন্য আপনার মাতৃভাষায় স্যুইচ করুন।",
      "faqTitle": "সচরাচর জিজ্ঞাস্য (FAQ)",
      "faq1Q": "এই অনলাইন টুলসগুলো কি ব্যবহারের জন্য সম্পূর্ণ ফ্রি?",
      "faq1A": "হ্যাঁ, অবশ্যই। আমাদের ক্যালকুলেটর, কনভার্টার এবং ওয়েব টুলসগুলো ১০০% ফ্রি। এখানে কোনো লুকানো ফি বা সাবস্ক্রিপশনের প্রয়োজন নেই।",
      "faq2Q": "ক্যালকুলেটরগুলো ব্যবহার করার জন্য কি আমাকে একটি অ্যাকাউন্ট তৈরি করতে হবে?",
      "faq2A": "কোনো সাইনআপ বা নিবন্ধনের প্রয়োজন নেই। কোনো ব্যক্তিগত তথ্য না দিয়েই আপনি অবিলম্বে আমাদের ওয়েবসাইটের প্রতিটি বৈশিষ্ট্য ব্যবহার করতে পারেন।",
      "faq3Q": "আমার ডেটা কি আপনার সার্ভারে সংরক্ষিত হয়?",
      "faq3A": "না। আমাদের বেশিরভাগ টুলই আপনার ওয়েব ব্রাউজারের মধ্যে স্থানীয়ভাবে ডেটা প্রক্রিয়া করে। আমরা আপনার ইনপুট করা কোনো ডেটা সংগ্রহ বা সংরক্ষণ করি না।",
      "faq4Q": "আর্থিক ক্যালকুলেটরগুলো কতটা সঠিক?",
      "faq4A": "আমাদের আর্থিক টুলসগুলো স্ট্যান্ডার্ড অ্যাকাউন্টিং সূত্র ব্যবহার করে তৈরি করা হয়েছে। তবে, এগুলো শুধুমাত্র তথ্যমূলক উদ্দেশ্যে এবং পেশাদার আর্থিক পরামর্শের বিকল্প নয়।",
      "faq5Q": "আমি কি আমার মোবাইল ফোনে এই ওয়েবসাইট ব্যবহার করতে পারি?",
      "faq5A": "হ্যাঁ, আমাদের প্ল্যাটফর্মটি সম্পূর্ণ রেসপন্সিভ। এটি স্মার্টফোন, ট্যাবলেট এবং ডেস্কটপ কম্পিউটারে নিখুঁতভাবে কাজ করার জন্য অপ্টিমাইজ করা হয়েছে।",
      "faq6Q": "কত ঘন ঘন নতুন টুল যোগ করা হয়?",
      "faq6A": "আমরা প্রতিনিয়ত আমাদের ডিরেক্টরি সম্প্রসারিত করছি। ব্যবহারকারীদের প্রতিক্রিয়ার ভিত্তিতে প্রতি সপ্তাহে নতুন ক্যালকুলেটর এবং টুলস যোগ করা হয়।",
      "ctaTitle": "আপনার কাজগুলো সহজ করতে প্রস্তুত?",
      "ctaDesc": "ম্যানুয়াল গণনায় আর সময় নষ্ট করবেন না। আজ থেকেই আমাদের ফ্রি অনলাইন টুলস ব্যবহার করা শুরু করুন এবং আপনার উৎপাদনশীলতা বাড়ান।",
      "ctaButton": "সব ক্যাটাগরি দেখুন"
    }
  }
};

import fs from 'fs';
for (const lang of Object.keys(content)) {
  const filePath = `messages/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data.Home = content[lang].Home;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}`);
  }
}
