const fs = require('fs');
const path = require('path');

const translations = {
  hi: {
    About: {
      title: "हमारे बारे में और कार्यप्रणाली",
      description: "100 Tools में आपका स्वागत है, जो प्रीमियम ऑनलाइन कैलकुलेटर और डेवलपर टूल्स के लिए आपका मुफ्त संसाधन है।",
      missionTitle: "हमारा मिशन",
      missionText: "हमारा मिशन रोजमर्रा के कार्यों के लिए तेज़, विश्वसनीय और गोपनीयता का सम्मान करने वाले टूल प्रदान करना है।",
      methodologyTitle: "हमारी कार्यप्रणाली",
      methodologyIntro: "हम विशेष रूप से वित्तीय और स्वास्थ्य उपकरणों के लिए पारदर्शिता और सटीकता में विश्वास करते हैं।",
      standardizedFormulasTitle: "मानकीकृत सूत्र",
      standardizedFormulasText: "सभी वित्तीय कैलकुलेटर उद्योग-मानक सूत्रों का उपयोग करते हैं।",
      medicalGuidelinesTitle: "चिकित्सा दिशानिर्देश",
      medicalGuidelinesText: "स्वास्थ्य कैलकुलेटर विश्व स्तर पर मान्यता प्राप्त समीकरणों का उपयोग करते हैं।",
      privacyFirstTitle: "गोपनीयता सबसे पहले",
      privacyFirstText: "आपका डेटा कभी भी आपके ब्राउज़र से बाहर नहीं जाता है। सभी गणनाएँ स्थानीय रूप से होती हैं।",
      continuousTestingTitle: "निरंतर परीक्षण",
      continuousTestingText: "हमारे उपकरणों का कड़ाई से परीक्षण किया जाता है ताकि त्रुटि रहित संचालन सुनिश्चित किया जा सके।",
      editorialGuidelinesTitle: "संपादकीय दिशानिर्देश",
      editorialGuidelinesText: "प्रत्येक टूल पेज को स्पष्ट और आसानी से उपयोग करने योग्य बनाया गया है।",
      disclaimer: "अस्वीकरण: इस वेबसाइट के उपकरण केवल सूचनात्मक उद्देश्यों के लिए हैं। यह कोई पेशेवर सलाह नहीं है।",
      teamTitle: "हम कौन हैं",
      teamText: "यह साइट हमारी टीम द्वारा संचालित है। हमसे संपर्क करने के लिए कृपया हमारा संपर्क पृष्ठ देखें।"
    },
    Privacy: {
      title: "गोपनीयता नीति",
      lastUpdated: "अंतिम अपडेट: 29 सितंबर 2026",
      intro: "100 Tools में, आपकी गोपनीयता हमारी सर्वोच्च प्राथमिकता है।",
      dataCollectionTitle: "कोई डेटा संग्रहण नहीं",
      dataCollectionText: "हम अनावश्यक रूप से व्यक्तिगत डेटा एकत्र नहीं करते हैं। गणना स्थानीय रूप से होती है।",
      analyticsTitle: "एनालिटिक्स",
      analyticsText: "हम ट्रैफ़िक को समझने के लिए गोपनीयता-अनुकूल एनालिटिक्स का उपयोग कर सकते हैं।",
      thirdPartyTitle: "थर्ड-पार्टी वेंडर और Google AdSense",
      thirdPartyText: "Google सहित तृतीय-पक्ष विक्रेता विज्ञापन दिखाने के लिए कुकीज़ का उपयोग करते हैं।",
      contactUs: "यदि इस नीति के बारे में आपके कोई प्रश्न हैं, तो कृपया हमसे संपर्क करें।",
      optOutTitle: "वैयक्तिकृत विज्ञापनों से ऑप्ट-आउट",
      optOutText: "आप Google विज्ञापन सेटिंग्स में जाकर वैयक्तिकृत विज्ञापनों से ऑप्ट-आउट कर सकते हैं।",
      userRightsTitle: "आपके गोपनीयता अधिकार",
      userRightsText: "आप फ़ुटर में 'गोपनीयता सेटिंग्स' का उपयोग करके अपनी सहमति प्रबंधित कर सकते हैं।",
      childrenTitle: "बच्चों की गोपनीयता",
      childrenText: "हम 13 वर्ष से कम उम्र के बच्चों से जानबूझकर जानकारी एकत्र नहीं करते हैं।",
      dataRetentionTitle: "डेटा प्रतिधारण",
      dataRetentionText: "अस्थायी कनेक्शन लॉग केवल सुरक्षा कारणों से रखे जाते हैं।"
    },
    Terms: {
      title: "सेवा की शर्तें",
      lastUpdated: "अंतिम अपडेट: 29 सितंबर 2026",
      intro: "100 Tools का उपयोग करके, आप इन शर्तों से सहमत होते हैं।",
      noWarrantyTitle: "कोई वारंटी नहीं",
      noWarrantyText: "सभी उपकरण 'जैसा है' के आधार पर बिना किसी वारंटी के प्रदान किए जाते हैं।",
      liabilityTitle: "दायित्व की सीमा",
      liabilityText: "हमारे उपकरणों के उपयोग से होने वाले किसी भी नुकसान के लिए 100 Tools उत्तरदायी नहीं होगा।",
      acceptableUseTitle: "स्वीकार्य उपयोग",
      acceptableUseText: "आप हमारे उपकरणों का उपयोग केवल कानूनी उद्देश्यों के लिए करने के लिए सहमत हैं।",
      modificationsTitle: "संशोधन",
      modificationsText: "हम बिना किसी सूचना के इन शर्तों को कभी भी बदल सकते हैं।"
    },
    Cookie: {
      title: "कुकी नीति",
      lastUpdated: "अंतिम अपडेट: 29 सितंबर 2026",
      intro: "यह नीति बताती है कि कुकीज़ क्या हैं और हम उनका उपयोग कैसे करते हैं।",
      whatAreCookiesTitle: "कुकीज़ क्या हैं?",
      whatAreCookiesText: "कुकीज़ छोटी टेक्स्ट फ़ाइलें हैं जो वेबसाइटें आपके डिवाइस पर रखती हैं।",
      howWeUseCookiesTitle: "हम कुकीज़ का उपयोग कैसे करते हैं",
      howWeUseCookiesText: "हम आवश्यक कार्यक्षमता और विज्ञापनों के लिए कुकीज़ का उपयोग करते हैं।",
      noTrackingTitle: "तृतीय-पक्ष विज्ञापन कुकीज़",
      noTrackingText: "हम Google AdSense का उपयोग करते हैं। आप फ़ुटर में अपनी प्राथमिकताएँ प्रबंधित कर सकते हैं।",
      managingCookiesTitle: "कुकीज़ का प्रबंधन",
      managingCookiesText: "आप अपने ब्राउज़र से कुकीज़ को हटा या ब्लॉक कर सकते हैं।"
    },
    Disclaimer: {
      title: "अस्वीकरण",
      lastUpdated: "अंतिम अपडेट: 29 सितंबर 2026",
      intro: "यहाँ दी गई जानकारी केवल सामान्य सूचनात्मक उद्देश्यों के लिए है।",
      accuracyTitle: "सामान्य सटीकता",
      accuracyText: "हम उत्पन्न परिणामों की सटीकता या पूर्णता की गारंटी नहीं देते हैं।",
      medicalTitle: "चिकित्सा अस्वीकरण",
      medicalText: "स्वास्थ्य कैलकुलेटर पेशेवर चिकित्सा सलाह का विकल्प नहीं हैं।",
      financialTitle: "वित्तीय अस्वीकरण",
      financialText: "वित्तीय कैलकुलेटर केवल उदाहरण के लिए हैं और वित्तीय सलाह नहीं हैं।",
      legalTitle: "कानूनी विविधताएँ",
      legalText: "सूत्र आपके अधिकार क्षेत्र में सटीक कर नियमों को नहीं दर्शा सकते हैं।"
    }
  },
  id: {
    About: {
      title: "Tentang Kami & Metodologi",
      description: "Selamat datang di 100 Tools, sumber daya gratis Anda untuk kalkulator online premium dan utilitas pengembang.",
      missionTitle: "Misi Kami",
      missionText: "Misi kami adalah menyediakan alat yang cepat, andal, dan menghormati privasi untuk tugas sehari-hari.",
      methodologyTitle: "Metodologi Kami",
      methodologyIntro: "Kami percaya pada transparansi dan akurasi, terutama untuk alat terkait keuangan dan kesehatan.",
      standardizedFormulasTitle: "Rumus Standar",
      standardizedFormulasText: "Semua kalkulator keuangan menggunakan rumus standar industri.",
      medicalGuidelinesTitle: "Pedoman Medis",
      medicalGuidelinesText: "Kalkulator kesehatan menggunakan persamaan yang diakui secara global.",
      privacyFirstTitle: "Privasi Pertama",
      privacyFirstText: "Data Anda tidak pernah meninggalkan browser Anda. Semua perhitungan dilakukan secara lokal.",
      continuousTestingTitle: "Pengujian Berkelanjutan",
      continuousTestingText: "Alat kami diuji secara ketat untuk memastikan tidak ada kesalahan.",
      editorialGuidelinesTitle: "Pedoman Editorial",
      editorialGuidelinesText: "Setiap halaman alat dirancang untuk menjadi intuitif dan mudah digunakan.",
      disclaimer: "Penafian: Alat dan kalkulator di situs web ini hanya untuk tujuan informasi dan pendidikan.",
      teamTitle: "Siapa Kami",
      teamText: "Situs ini dioperasikan oleh tim kami. Untuk menghubungi kami, silakan lihat halaman Kontak."
    },
    Privacy: {
      title: "Kebijakan Privasi",
      lastUpdated: "Terakhir Diperbarui: 29 September 2026",
      intro: "Di 100 Tools, privasi Anda adalah prioritas utama kami.",
      dataCollectionTitle: "Tidak Ada Pengumpulan Data",
      dataCollectionText: "Kami tidak mengumpulkan data pribadi yang tidak perlu. Perhitungan terjadi secara lokal.",
      analyticsTitle: "Analitik & Pelacakan",
      analyticsText: "Kami mungkin menggunakan analitik yang menghormati privasi untuk memahami lalu lintas situs.",
      thirdPartyTitle: "Vendor Pihak Ketiga & Google AdSense",
      thirdPartyText: "Vendor pihak ketiga, termasuk Google, menggunakan cookie untuk menayangkan iklan.",
      contactUs: "Jika Anda memiliki pertanyaan tentang Kebijakan Privasi ini, silakan hubungi kami.",
      optOutTitle: "Menyisih dari Iklan yang Dipersonalisasi",
      optOutText: "Anda dapat menyisih dari iklan hasil personalisasi di Pengaturan Iklan Google.",
      userRightsTitle: "Hak Privasi Anda (GDPR & CCPA)",
      userRightsText: "Kelola persetujuan Anda melalui tautan 'Pengaturan privasi' di footer.",
      childrenTitle: "Privasi Anak-anak",
      childrenText: "Kami tidak dengan sengaja mengumpulkan informasi dari anak di bawah 13 tahun.",
      dataRetentionTitle: "Penyimpanan Data",
      dataRetentionText: "Log koneksi sementara disimpan hanya untuk tujuan keamanan."
    },
    Terms: {
      title: "Ketentuan Layanan",
      lastUpdated: "Terakhir Diperbarui: 29 September 2026",
      intro: "Dengan mengakses dan menggunakan 100 Tools, Anda setuju untuk mematuhi ketentuan ini.",
      noWarrantyTitle: "Tidak Ada Jaminan (Apa Adanya)",
      noWarrantyText: "Semua alat disediakan 'apa adanya' tanpa jaminan apa pun.",
      liabilityTitle: "Batasan Tanggung Jawab",
      liabilityText: "100 Tools tidak bertanggung jawab atas kerusakan apa pun yang timbul dari penggunaan alat kami.",
      acceptableUseTitle: "Penggunaan yang Dapat Diterima",
      acceptableUseText: "Anda setuju untuk menggunakan alat kami hanya untuk tujuan yang sah.",
      modificationsTitle: "Modifikasi",
      modificationsText: "Kami berhak untuk merevisi ketentuan ini kapan saja tanpa pemberitahuan."
    },
    Cookie: {
      title: "Kebijakan Cookie",
      lastUpdated: "Terakhir Diperbarui: 29 September 2026",
      intro: "Kebijakan ini menjelaskan apa itu cookie dan bagaimana kami menggunakannya.",
      whatAreCookiesTitle: "Apa itu Cookie?",
      whatAreCookiesText: "Cookie adalah file teks kecil yang ditempatkan di perangkat Anda.",
      howWeUseCookiesTitle: "Bagaimana Kami Menggunakan Cookie",
      howWeUseCookiesText: "Kami menggunakan cookie untuk fungsionalitas penting dan iklan.",
      noTrackingTitle: "Cookie Iklan Pihak Ketiga",
      noTrackingText: "Kami menggunakan Google AdSense. Anda dapat mengelola preferensi Anda di footer.",
      managingCookiesTitle: "Mengelola Cookie",
      managingCookiesText: "Anda dapat menghapus atau memblokir cookie dari browser Anda."
    },
    Disclaimer: {
      title: "Penafian",
      lastUpdated: "Terakhir Diperbarui: 29 September 2026",
      intro: "Informasi di 100 Tools hanya untuk tujuan informasi umum.",
      accuracyTitle: "Akurasi Umum",
      accuracyText: "Kami tidak menjamin keakuratan hasil yang dihasilkan.",
      medicalTitle: "Penafian Medis",
      medicalText: "Kalkulator kesehatan bukanlah pengganti nasihat medis profesional.",
      financialTitle: "Penafian Finansial",
      financialText: "Kalkulator keuangan hanya untuk ilustrasi dan bukan nasihat keuangan.",
      legalTitle: "Variasi Hukum",
      legalText: "Rumus mungkin tidak mencerminkan aturan pajak yang tepat di wilayah Anda."
    }
  },
  it: {
    About: {
      title: "Chi siamo e Metodologia",
      description: "Benvenuto su 100 Tools, la tua risorsa gratuita per calcolatrici premium online e strumenti per sviluppatori.",
      missionTitle: "La nostra missione",
      missionText: "La nostra missione è fornire strumenti veloci, affidabili e rispettosi della privacy per le attività quotidiane.",
      methodologyTitle: "La nostra metodologia",
      methodologyIntro: "Crediamo nella trasparenza e nell'accuratezza, in particolare per gli strumenti finanziari e sanitari.",
      standardizedFormulasTitle: "Formule standardizzate",
      standardizedFormulasText: "Tutte le calcolatrici finanziarie utilizzano formule standard del settore.",
      medicalGuidelinesTitle: "Linee guida mediche",
      medicalGuidelinesText: "Le calcolatrici sanitarie utilizzano equazioni riconosciute a livello globale.",
      privacyFirstTitle: "La privacy prima di tutto",
      privacyFirstText: "I tuoi dati non lasciano mai il tuo browser. Tutti i calcoli avvengono localmente.",
      continuousTestingTitle: "Test continui",
      continuousTestingText: "I nostri strumenti sono rigorosamente testati per garantire l'assenza di errori.",
      editorialGuidelinesTitle: "Linee guida editoriali",
      editorialGuidelinesText: "Ogni pagina è progettata per essere intuitiva e di facile utilizzo.",
      disclaimer: "Avvertenza: Gli strumenti su questo sito sono solo a scopo informativo ed educativo.",
      teamTitle: "Chi siamo",
      teamText: "Questo sito è gestito dal nostro team. Per contattarci, visita la pagina Contatti."
    },
    Privacy: {
      title: "Informativa sulla privacy",
      lastUpdated: "Ultimo aggiornamento: 29 settembre 2026",
      intro: "Su 100 Tools, la tua privacy è la nostra massima priorità.",
      dataCollectionTitle: "Nessuna raccolta di dati",
      dataCollectionText: "Non raccogliamo dati personali inutilmente. I calcoli avvengono localmente.",
      analyticsTitle: "Analitica e tracciamento",
      analyticsText: "Potremmo utilizzare analisi rispettose della privacy per comprendere il traffico.",
      thirdPartyTitle: "Fornitori di terze parti e Google AdSense",
      thirdPartyText: "I fornitori di terze parti, tra cui Google, utilizzano i cookie per pubblicare annunci.",
      contactUs: "In caso di domande, ti preghiamo di contattarci.",
      optOutTitle: "Rinuncia agli annunci personalizzati",
      optOutText: "Puoi disattivare la pubblicità personalizzata nelle Impostazioni annunci di Google.",
      userRightsTitle: "I tuoi diritti (GDPR e CCPA)",
      userRightsText: "Gestisci il tuo consenso tramite il link 'Impostazioni sulla privacy' nel piè di pagina.",
      childrenTitle: "Privacy dei bambini",
      childrenText: "Non raccogliamo consapevolmente informazioni da minori di 13 anni.",
      dataRetentionTitle: "Conservazione dei dati",
      dataRetentionText: "I log di connessione temporanei vengono conservati solo per motivi di sicurezza."
    },
    Terms: {
      title: "Termini di servizio",
      lastUpdated: "Ultimo aggiornamento: 29 settembre 2026",
      intro: "Accedendo a 100 Tools, accetti questi termini.",
      noWarrantyTitle: "Nessuna garanzia",
      noWarrantyText: "Tutti gli strumenti sono forniti 'così come sono' senza alcuna garanzia.",
      liabilityTitle: "Limitazione di responsabilità",
      liabilityText: "In nessun caso 100 Tools sarà responsabile per danni derivanti dall'uso dei nostri strumenti.",
      acceptableUseTitle: "Uso accettabile",
      acceptableUseText: "Accetti di utilizzare i nostri strumenti solo per scopi legali.",
      modificationsTitle: "Modifiche",
      modificationsText: "Possiamo modificare questi termini in qualsiasi momento senza preavviso."
    },
    Cookie: {
      title: "Informativa sui cookie",
      lastUpdated: "Ultimo aggiornamento: 29 settembre 2026",
      intro: "Questa politica spiega cosa sono i cookie e come li utilizziamo.",
      whatAreCookiesTitle: "Cosa sono i cookie?",
      whatAreCookiesText: "I cookie sono piccoli file di testo posizionati sul tuo dispositivo.",
      howWeUseCookiesTitle: "Come utilizziamo i cookie",
      howWeUseCookiesText: "Utilizziamo i cookie per funzionalità essenziali e per la pubblicità tramite terze parti come Google.",
      noTrackingTitle: "Cookie pubblicitari di terze parti",
      noTrackingText: "Utilizziamo Google AdSense. Puoi gestire le tue preferenze nel piè di pagina.",
      managingCookiesTitle: "Gestione dei cookie",
      managingCookiesText: "Puoi eliminare o bloccare i cookie dal tuo browser."
    },
    Disclaimer: {
      title: "Avvertenze",
      lastUpdated: "Ultimo aggiornamento: 29 settembre 2026",
      intro: "Le informazioni fornite su 100 Tools sono solo a scopo informativo generale.",
      accuracyTitle: "Accuratezza generale",
      accuracyText: "Non offriamo garanzie sulla completezza o accuratezza dei risultati.",
      medicalTitle: "Avvertenza medica",
      medicalText: "Le calcolatrici sanitarie non sostituiscono la consulenza medica professionale.",
      financialTitle: "Avvertenza finanziaria",
      financialText: "Le calcolatrici finanziarie sono solo a scopo illustrativo.",
      legalTitle: "Variazioni legali",
      legalText: "Le formule potrebbero non riflettere le precise regole fiscali della tua giurisdizione."
    }
  },
  ja: {
    About: {
      title: "私たちについて＆方法論",
      description: "100 Toolsへようこそ。ここはプレミアムオンライン計算機と開発者ユーティリティの無料リソースです。",
      missionTitle: "私たちの使命",
      missionText: "私たちの使命は、日常業務において高速で信頼性が高く、プライバシーを尊重するツールを提供することです。",
      methodologyTitle: "私たちの方法論",
      methodologyIntro: "私たちは透明性と正確性を信じています。",
      standardizedFormulasTitle: "標準化された公式",
      standardizedFormulasText: "すべての財務計算機は業界標準の公式を使用しています。",
      medicalGuidelinesTitle: "医療ガイドライン",
      medicalGuidelinesText: "健康計算機は世界的に認められた方程式を使用しています。",
      privacyFirstTitle: "プライバシー第一",
      privacyFirstText: "データがブラウザから出ることはありません。すべての計算はローカルで行われます。",
      continuousTestingTitle: "継続的なテスト",
      continuousTestingText: "私たちのツールは正確性を確保するために厳密にテストされています。",
      editorialGuidelinesTitle: "編集ガイドライン",
      editorialGuidelinesText: "各ページは直感的で使いやすいように設計されています。",
      disclaimer: "免責事項：当サイトのツールは情報提供のみを目的としており、専門的なアドバイスではありません。",
      teamTitle: "私たちについて",
      teamText: "このサイトは私たちのチームによって運営されています。お問い合わせはコンタクトページをご覧ください。"
    },
    Privacy: {
      title: "プライバシーポリシー",
      lastUpdated: "最終更新日：2026年9月29日",
      intro: "100 Toolsでは、あなたのプライバシーが最優先事項です。",
      dataCollectionTitle: "データ収集なし",
      dataCollectionText: "不必要に個人データを収集することはありません。計算はローカルで行われます。",
      analyticsTitle: "分析と追跡",
      analyticsText: "トラフィックを理解するためにプライバシーに配慮した分析を使用する場合があります。",
      thirdPartyTitle: "サードパーティおよびGoogle AdSense",
      thirdPartyText: "Googleなどのサードパーティは、Cookieを使用して広告を配信します。",
      contactUs: "ご質問がある場合は、お問い合わせください。",
      optOutTitle: "パーソナライズド広告のオプトアウト",
      optOutText: "Google広告設定でパーソナライズド広告をオプトアウトできます。",
      userRightsTitle: "プライバシーの権利",
      userRightsText: "フッターの「プライバシー設定」リンクを使用して同意を管理できます。",
      childrenTitle: "子供のプライバシー",
      childrenText: "13歳未満の子供から情報を意図的に収集することはありません。",
      dataRetentionTitle: "データ保持",
      dataRetentionText: "一時的な接続ログはセキュリティの目的でのみ保持されます。"
    },
    Terms: {
      title: "利用規約",
      lastUpdated: "最終更新日：2026年9月29日",
      intro: "100 Toolsを使用することにより、これらの規約に同意したことになります。",
      noWarrantyTitle: "保証なし",
      noWarrantyText: "すべてのツールは「現状有姿」で提供され、保証はありません。",
      liabilityTitle: "責任の制限",
      liabilityText: "100 Toolsは、私たちのツールの使用から生じるいかなる損害についても責任を負いません。",
      acceptableUseTitle: "許容される使用",
      acceptableUseText: "ツールを合法的な目的でのみ使用することに同意するものとします。",
      modificationsTitle: "変更",
      modificationsText: "これらの規約を予告なく変更することがあります。"
    },
    Cookie: {
      title: "Cookieポリシー",
      lastUpdated: "最終更新日：2026年9月29日",
      intro: "このポリシーは、Cookieとは何か、またその使用方法を説明しています。",
      whatAreCookiesTitle: "Cookieとは？",
      whatAreCookiesText: "Cookieは、お使いのデバイスに配置される小さなテキストファイルです。",
      howWeUseCookiesTitle: "Cookieの使用方法",
      howWeUseCookiesText: "不可欠な機能と広告のためにCookieを使用します。",
      noTrackingTitle: "サードパーティ広告Cookie",
      noTrackingText: "Google AdSenseを使用しています。設定はフッターで管理できます。",
      managingCookiesTitle: "Cookieの管理",
      managingCookiesText: "ブラウザからCookieを削除またはブロックできます。"
    },
    Disclaimer: {
      title: "免責事項",
      lastUpdated: "最終更新日：2026年9月29日",
      intro: "100 Toolsの情報は一般的な情報提供のみを目的としています。",
      accuracyTitle: "一般的な正確性",
      accuracyText: "結果の正確性や完全性を保証するものではありません。",
      medicalTitle: "医療免責事項",
      medicalText: "健康計算機は専門的な医療アドバイスの代わりにはなりません。",
      financialTitle: "財務免責事項",
      financialText: "財務計算機は説明のみを目的としており、財務アドバイスではありません。",
      legalTitle: "法的な違い",
      legalText: "公式は、お住まいの地域の正確な税制を反映していない場合があります。"
    }
  },
  ko: {
    About: {
      title: "소개 및 방법론",
      description: "프리미엄 온라인 계산기 및 개발자 유틸리티를 위한 무료 리소스인 100 Tools에 오신 것을 환영합니다.",
      missionTitle: "우리의 사명",
      missionText: "우리의 사명은 일상적인 작업을 위해 빠르고 안정적이며 개인 정보 보호를 존중하는 도구를 제공하는 것입니다.",
      methodologyTitle: "우리의 방법론",
      methodologyIntro: "우리는 투명성과 정확성을 믿습니다.",
      standardizedFormulasTitle: "표준화된 공식",
      standardizedFormulasText: "모든 재무 계산기는 업계 표준 공식을 사용합니다.",
      medicalGuidelinesTitle: "의료 가이드라인",
      medicalGuidelinesText: "건강 계산기는 세계적으로 인정받는 방정식을 사용합니다.",
      privacyFirstTitle: "개인 정보 우선",
      privacyFirstText: "데이터는 브라우저를 떠나지 않습니다. 모든 계산은 로컬에서 수행됩니다.",
      continuousTestingTitle: "지속적인 테스트",
      continuousTestingText: "우리의 도구는 정확성을 보장하기 위해 엄격하게 테스트됩니다.",
      editorialGuidelinesTitle: "편집 가이드라인",
      editorialGuidelinesText: "각 페이지는 직관적이고 사용하기 쉽도록 설계되었습니다.",
      disclaimer: "면책 조항: 당사 사이트의 도구는 정보 제공의 목적으로만 제공되며 전문적인 조언이 아닙니다.",
      teamTitle: "우리는 누구인가",
      teamText: "이 사이트는 우리 팀이 운영합니다. 저희에게 연락하려면 연락처 페이지를 참조하십시오."
    },
    Privacy: {
      title: "개인정보 처리방침",
      lastUpdated: "최종 업데이트: 2026년 9월 29일",
      intro: "100 Tools에서는 개인 정보 보호가 최우선입니다.",
      dataCollectionTitle: "데이터 수집 없음",
      dataCollectionText: "불필요하게 개인 데이터를 수집하지 않습니다. 계산은 로컬에서 이루어집니다.",
      analyticsTitle: "분석 및 추적",
      analyticsText: "트래픽을 이해하기 위해 개인 정보를 보호하는 분석을 사용할 수 있습니다.",
      thirdPartyTitle: "타사 공급업체 및 Google AdSense",
      thirdPartyText: "Google을 포함한 타사 공급업체는 쿠키를 사용하여 광고를 게재합니다.",
      contactUs: "질문이 있으시면 저희에게 연락하십시오.",
      optOutTitle: "맞춤설정 광고 선택 해제",
      optOutText: "Google 광고 설정에서 맞춤 광고를 선택 해제할 수 있습니다.",
      userRightsTitle: "귀하의 권리",
      userRightsText: "바닥글의 '개인정보 설정' 링크를 사용하여 동의를 관리할 수 있습니다.",
      childrenTitle: "어린이 개인 정보 보호",
      childrenText: "당사는 13세 미만의 어린이로부터 의도적으로 정보를 수집하지 않습니다.",
      dataRetentionTitle: "데이터 보존",
      dataRetentionText: "임시 연결 로그는 보안 목적으로만 보관됩니다."
    },
    Terms: {
      title: "서비스 약관",
      lastUpdated: "최종 업데이트: 2026년 9월 29일",
      intro: "100 Tools를 사용함으로써 귀하는 이 약관에 동의하게 됩니다.",
      noWarrantyTitle: "보증 없음",
      noWarrantyText: "모든 도구는 '있는 그대로' 제공되며 어떠한 보증도 없습니다.",
      liabilityTitle: "책임의 한계",
      liabilityText: "100 Tools는 도구 사용으로 인해 발생하는 손해에 대해 책임을 지지 않습니다.",
      acceptableUseTitle: "허용 가능한 사용",
      acceptableUseText: "도구를 합법적인 목적으로만 사용하는 데 동의합니다.",
      modificationsTitle: "수정",
      modificationsText: "당사는 사전 통지 없이 언제든지 이 약관을 수정할 수 있습니다."
    },
    Cookie: {
      title: "쿠키 정책",
      lastUpdated: "최종 업데이트: 2026년 9월 29일",
      intro: "이 정책은 쿠키가 무엇이며 우리가 어떻게 사용하는지 설명합니다.",
      whatAreCookiesTitle: "쿠키란?",
      whatAreCookiesText: "쿠키는 기기에 배치되는 작은 텍스트 파일입니다.",
      howWeUseCookiesTitle: "쿠키 사용 방법",
      howWeUseCookiesText: "당사는 필수 기능과 광고를 위해 쿠키를 사용합니다.",
      noTrackingTitle: "타사 광고 쿠키",
      noTrackingText: "Google AdSense를 사용합니다. 바닥글에서 환경설정을 관리할 수 있습니다.",
      managingCookiesTitle: "쿠키 관리",
      managingCookiesText: "브라우저에서 쿠키를 삭제하거나 차단할 수 있습니다."
    },
    Disclaimer: {
      title: "면책 조항",
      lastUpdated: "최종 업데이트: 2026년 9월 29일",
      intro: "100 Tools의 정보는 일반적인 정보 제공 목적으로만 제공됩니다.",
      accuracyTitle: "일반적인 정확성",
      accuracyText: "당사는 결과의 정확성을 보장하지 않습니다.",
      medicalTitle: "의료 면책 조항",
      medicalText: "건강 계산기는 전문적인 의학적 조언을 대신하지 않습니다.",
      financialTitle: "재무 면책 조항",
      financialText: "재무 계산기는 재무 조언이 아닙니다.",
      legalTitle: "법적 변동 사항",
      legalText: "공식은 귀하의 관할권의 정확한 세금 규정을 반영하지 않을 수 있습니다."
    }
  }
};

for (const [lang, texts] of Object.entries(translations)) {
  const filePath = path.join(process.cwd(), 'messages', `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data.About = texts.About;
    data.Privacy = texts.Privacy;
    data.Terms = texts.Terms;
    data.Cookie = texts.Cookie;
    data.Disclaimer = texts.Disclaimer;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`Updated ${lang}.json`);
  }
}
