const fs = require('fs');
const path = require('path');

const translations = {
  ar: {
    title: "نحن نقدر خصوصيتك",
    description: "نستخدم نحن وشركاؤنا ملفات تعريف الارتباط لتخزين و/أو الوصول إلى المعلومات على جهازك. يُستخدم هذا لتقديم إعلانات ومحتوى مخصص، وقياس أداء الإعلانات والمحتوى، واكتساب رؤى حول الجمهور.",
    acceptAll: "قبول الكل",
    rejectAll: "رفض غير الأساسي",
    managePreferences: "إدارة التفضيلات",
    savePreferences: "حفظ التفضيلات",
    essentialCookies: "ملفات تعريف الارتباط الأساسية (مطلوبة)",
    essentialCookiesDesc: "ضرورية لكي يعمل الموقع بشكل صحيح.",
    analyticsCookies: "ملفات تعريف الارتباط التحليلية",
    analyticsCookiesDesc: "تساعدنا في فهم كيفية تفاعل الزوار مع الموقع.",
    adCookies: "ملفات تعريف الارتباط الإعلانية",
    adCookiesDesc: "تُستخدم من قبلنا وشركائنا (مثل Google) لتقديم إعلانات مخصصة.",
    close: "إغلاق"
  },
  bn: {
    title: "আমরা আপনার গোপনীয়তার মূল্যায়ন করি",
    description: "আমরা এবং আমাদের অংশীদাররা আপনার ডিভাইসে তথ্য সঞ্চয় এবং/অথবা অ্যাক্সেস করতে কুকি ব্যবহার করি। এটি ব্যক্তিগতকৃত বিজ্ঞাপন এবং সামগ্রী পরিবেশন করতে, বিজ্ঞাপন এবং সামগ্রীর কার্যকারিতা পরিমাপ করতে এবং দর্শকদের অন্তর্দৃষ্টি অর্জন করতে ব্যবহৃত হয়।",
    acceptAll: "সব গ্রহণ করুন",
    rejectAll: "অপ্রয়োজনীয় প্রত্যাখ্যান করুন",
    managePreferences: "পছন্দ পরিচালনা করুন",
    savePreferences: "পছন্দ সংরক্ষণ করুন",
    essentialCookies: "প্রয়োজনীয় কুকি (আবশ্যক)",
    essentialCookiesDesc: "ওয়েবসাইটটি সঠিকভাবে কাজ করার জন্য প্রয়োজনীয়।",
    analyticsCookies: "অ্যানালিটিক্স কুকি",
    analyticsCookiesDesc: "দর্শকরা সাইটের সাথে কীভাবে যোগাযোগ করে তা বুঝতে আমাদের সহায়তা করে।",
    adCookies: "বিজ্ঞাপন কুকি",
    adCookiesDesc: "ব্যক্তিগতকৃত বিজ্ঞাপন পরিবেশন করতে আমাদের এবং আমাদের অংশীদারদের (যেমন Google) দ্বারা ব্যবহৃত হয়।",
    close: "বন্ধ করুন"
  },
  de: {
    title: "Wir schätzen Ihre Privatsphäre",
    description: "Wir und unsere Partner verwenden Cookies, um Informationen auf Ihrem Gerät zu speichern und/oder darauf zuzugreifen. Dies dient dazu, personalisierte Anzeigen und Inhalte bereitzustellen, die Anzeigen- und Inhaltsleistung zu messen und Erkenntnisse über Zielgruppen zu gewinnen.",
    acceptAll: "Alle akzeptieren",
    rejectAll: "Nicht-essenzielle ablehnen",
    managePreferences: "Einstellungen verwalten",
    savePreferences: "Einstellungen speichern",
    essentialCookies: "Essenzielle Cookies (Erforderlich)",
    essentialCookiesDesc: "Notwendig, damit die Website ordnungsgemäß funktioniert.",
    analyticsCookies: "Analyse-Cookies",
    analyticsCookiesDesc: "Helfen uns zu verstehen, wie Besucher mit der Website interagieren.",
    adCookies: "Werbe-Cookies",
    adCookiesDesc: "Werden von uns und unseren Partnern (wie Google) verwendet, um personalisierte Anzeigen bereitzustellen.",
    close: "Schließen"
  },
  es: {
    title: "Valoramos su privacidad",
    description: "Nosotros y nuestros socios utilizamos cookies para almacenar y/o acceder a la información de su dispositivo. Esto se utiliza para mostrar anuncios y contenido personalizados, medir el rendimiento de los anuncios y el contenido, y obtener información sobre la audiencia.",
    acceptAll: "Aceptar todo",
    rejectAll: "Rechazar no esenciales",
    managePreferences: "Gestionar preferencias",
    savePreferences: "Guardar preferencias",
    essentialCookies: "Cookies esenciales (Obligatorio)",
    essentialCookiesDesc: "Necesarias para que el sitio web funcione correctamente.",
    analyticsCookies: "Cookies analíticas",
    analyticsCookiesDesc: "Nos ayudan a comprender cómo interactúan los visitantes con el sitio.",
    adCookies: "Cookies publicitarias",
    adCookiesDesc: "Utilizadas por nosotros y nuestros socios (como Google) para mostrar anuncios personalizados.",
    close: "Cerrar"
  },
  fr: {
    title: "Nous respectons votre vie privée",
    description: "Nous et nos partenaires utilisons des cookies pour stocker et/ou accéder à des informations sur votre appareil. Ceci est utilisé pour diffuser des annonces et du contenu personnalisés, mesurer les performances des annonces et du contenu, et obtenir des informations sur l'audience.",
    acceptAll: "Tout accepter",
    rejectAll: "Rejeter les non-essentiels",
    managePreferences: "Gérer les préférences",
    savePreferences: "Enregistrer les préférences",
    essentialCookies: "Cookies essentiels (Requis)",
    essentialCookiesDesc: "Nécessaires au bon fonctionnement du site Web.",
    analyticsCookies: "Cookies analytiques",
    analyticsCookiesDesc: "Nous aident à comprendre comment les visiteurs interagissent avec le site.",
    adCookies: "Cookies publicitaires",
    adCookiesDesc: "Utilisés par nous et nos partenaires (comme Google) pour diffuser des annonces personnalisées.",
    close: "Fermer"
  },
  hi: {
    title: "हम आपकी गोपनीयता को महत्व देते हैं",
    description: "हम और हमारे भागीदार आपके डिवाइस पर जानकारी संग्रहीत करने और/या उस तक पहुंचने के लिए कुकीज़ का उपयोग करते हैं। इसका उपयोग वैयक्तिकृत विज्ञापन और सामग्री परोसने, विज्ञापन और सामग्री के प्रदर्शन को मापने और दर्शकों की जानकारी प्राप्त करने के लिए किया जाता है।",
    acceptAll: "सभी स्वीकार करें",
    rejectAll: "गैर-आवश्यक अस्वीकार करें",
    managePreferences: "प्राथमिकताएं प्रबंधित करें",
    savePreferences: "प्राथमिकताएं सहेजें",
    essentialCookies: "आवश्यक कुकीज़ (अनिवार्य)",
    essentialCookiesDesc: "वेबसाइट को ठीक से काम करने के लिए आवश्यक है।",
    analyticsCookies: "एनालिटिक्स कुकीज़",
    analyticsCookiesDesc: "यह समझने में हमारी मदद करें कि विज़िटर साइट के साथ कैसे इंटरैक्ट करते हैं।",
    adCookies: "विज्ञापन कुकीज़",
    adCookiesDesc: "हमारे और हमारे भागीदारों (जैसे Google) द्वारा वैयक्तिकृत विज्ञापन परोसने के लिए उपयोग किया जाता है।",
    close: "बंद करें"
  },
  id: {
    title: "Kami menghargai privasi Anda",
    description: "Kami dan mitra kami menggunakan cookie untuk menyimpan dan/atau mengakses informasi di perangkat Anda. Ini digunakan untuk menyajikan iklan dan konten yang dipersonalisasi, mengukur kinerja iklan dan konten, dan mendapatkan wawasan audiens.",
    acceptAll: "Terima Semua",
    rejectAll: "Tolak Non-Esensial",
    managePreferences: "Kelola Preferensi",
    savePreferences: "Simpan Preferensi",
    essentialCookies: "Cookie Esensial (Diperlukan)",
    essentialCookiesDesc: "Diperlukan agar situs web berfungsi dengan baik.",
    analyticsCookies: "Cookie Analitik",
    analyticsCookiesDesc: "Membantu kami memahami bagaimana pengunjung berinteraksi dengan situs.",
    adCookies: "Cookie Iklan",
    adCookiesDesc: "Digunakan oleh kami dan mitra kami (seperti Google) untuk menyajikan iklan yang dipersonalisasi.",
    close: "Tutup"
  },
  it: {
    title: "Diamo valore alla tua privacy",
    description: "Noi e i nostri partner utilizziamo i cookie per archiviare e/o accedere alle informazioni sul tuo dispositivo. Questo serve per fornire annunci e contenuti personalizzati, misurare le prestazioni di annunci e contenuti e acquisire informazioni sul pubblico.",
    acceptAll: "Accetta tutto",
    rejectAll: "Rifiuta non essenziali",
    managePreferences: "Gestisci preferenze",
    savePreferences: "Salva preferenze",
    essentialCookies: "Cookie essenziali (Obbligatori)",
    essentialCookiesDesc: "Necessari per il corretto funzionamento del sito web.",
    analyticsCookies: "Cookie analitici",
    analyticsCookiesDesc: "Ci aiutano a capire come i visitatori interagiscono con il sito.",
    adCookies: "Cookie pubblicitari",
    adCookiesDesc: "Utilizzati da noi e dai nostri partner (come Google) per fornire annunci personalizzati.",
    close: "Chiudi"
  },
  ja: {
    title: "私たちはあなたのプライバシーを尊重します",
    description: "私たちと私たちのパートナーは、デバイス上の情報を保存および/またはアクセスするためにCookieを使用します。これは、パーソナライズされた広告とコンテンツの配信、広告とコンテンツのパフォーマンスの測定、および視聴者の洞察の獲得に使用されます。",
    acceptAll: "すべて受け入れる",
    rejectAll: "不可欠でないものを拒否する",
    managePreferences: "設定を管理する",
    savePreferences: "設定を保存する",
    essentialCookies: "不可欠なCookie（必須）",
    essentialCookiesDesc: "ウェブサイトが適切に機能するために必要です。",
    analyticsCookies: "分析Cookie",
    analyticsCookiesDesc: "訪問者がサイトとどのようにやり取りするかを理解するのに役立ちます。",
    adCookies: "広告Cookie",
    adCookiesDesc: "パーソナライズされた広告を配信するために、私たちと私たちのパートナー（Googleなど）によって使用されます。",
    close: "閉じる"
  },
  ko: {
    title: "귀하의 개인 정보를 소중하게 생각합니다",
    description: "당사와 파트너는 기기의 정보를 저장하거나 액세스하기 위해 쿠키를 사용합니다. 이는 맞춤형 광고 및 콘텐츠를 제공하고, 광고 및 콘텐츠 실적을 측정하며, 잠재고객에 대한 통찰력을 얻는 데 사용됩니다.",
    acceptAll: "모두 수락",
    rejectAll: "필수적이지 않은 것 거부",
    managePreferences: "기본 설정 관리",
    savePreferences: "기본 설정 저장",
    essentialCookies: "필수 쿠키(필수)",
    essentialCookiesDesc: "웹사이트가 제대로 작동하는 데 필요합니다.",
    analyticsCookies: "분석 쿠키",
    analyticsCookiesDesc: "방문자가 사이트와 상호 작용하는 방식을 이해하는 데 도움이 됩니다.",
    adCookies: "광고 쿠키",
    adCookiesDesc: "당사와 파트너(Google 등)가 맞춤형 광고를 제공하는 데 사용합니다.",
    close: "닫기"
  },
  nl: {
    title: "Wij waarderen uw privacy",
    description: "Wij en onze partners gebruiken cookies om informatie op uw apparaat op te slaan en/of te openen. Dit wordt gebruikt om gepersonaliseerde advertenties en content te leveren, de prestaties van advertenties en content te meten en inzichten in het publiek te verkrijgen.",
    acceptAll: "Alles accepteren",
    rejectAll: "Niet-essentiële weigeren",
    managePreferences: "Voorkeuren beheren",
    savePreferences: "Voorkeuren opslaan",
    essentialCookies: "Essentiële Cookies (Vereist)",
    essentialCookiesDesc: "Noodzakelijk om de website goed te laten functioneren.",
    analyticsCookies: "Analytische Cookies",
    analyticsCookiesDesc: "Helpen ons te begrijpen hoe bezoekers omgaan met de site.",
    adCookies: "Advertentiecookies",
    adCookiesDesc: "Gebruikt door ons en onze partners (zoals Google) om gepersonaliseerde advertenties weer te geven.",
    close: "Sluiten"
  },
  pl: {
    title: "Cenimy Twoją prywatność",
    description: "My i nasi partnerzy używamy plików cookie do przechowywania i/lub uzyskiwania dostępu do informacji na Twoim urządzeniu. Służy to do wyświetlania spersonalizowanych reklam i treści, mierzenia wydajności reklam i treści oraz zdobywania wiedzy o odbiorcach.",
    acceptAll: "Akceptuj wszystko",
    rejectAll: "Odrzuć nieistotne",
    managePreferences: "Zarządzaj preferencjami",
    savePreferences: "Zapisz preferencje",
    essentialCookies: "Niezbędne pliki cookie (Wymagane)",
    essentialCookiesDesc: "Niezbędne do prawidłowego funkcjonowania witryny.",
    analyticsCookies: "Analityczne pliki cookie",
    analyticsCookiesDesc: "Pomagają nam zrozumieć, w jaki sposób odwiedzający wchodzą w interakcję z witryną.",
    adCookies: "Reklamowe pliki cookie",
    adCookiesDesc: "Używane przez nas i naszych partnerów (np. Google) do wyświetlania spersonalizowanych reklam.",
    close: "Zamknij"
  },
  pt: {
    title: "Valorizamos a sua privacidade",
    description: "Nós e os nossos parceiros utilizamos cookies para armazenar e/ou aceder a informações no seu dispositivo. Isso é usado para fornecer anúncios e conteúdo personalizados, medir o desempenho de anúncios e conteúdo e obter insights sobre o público.",
    acceptAll: "Aceitar Todos",
    rejectAll: "Rejeitar Não Essenciais",
    managePreferences: "Gerenciar Preferências",
    savePreferences: "Salvar Preferências",
    essentialCookies: "Cookies Essenciais (Obrigatório)",
    essentialCookiesDesc: "Necessários para que o site funcione corretamente.",
    analyticsCookies: "Cookies Analíticos",
    analyticsCookiesDesc: "Ajudam-nos a entender como os visitantes interagem com o site.",
    adCookies: "Cookies de Publicidade",
    adCookiesDesc: "Usados por nós e nossos parceiros (como o Google) para veicular anúncios personalizados.",
    close: "Fechar"
  },
  ru: {
    title: "Мы ценим вашу конфиденциальность",
    description: "Мы и наши партнеры используем файлы cookie для хранения и/или доступа к информации на вашем устройстве. Это используется для показа персонализированной рекламы и контента, измерения эффективности рекламы и контента, а также для получения информации об аудитории.",
    acceptAll: "Принять все",
    rejectAll: "Отклонить необязательные",
    managePreferences: "Управление настройками",
    savePreferences: "Сохранить настройки",
    essentialCookies: "Основные файлы cookie (Обязательно)",
    essentialCookiesDesc: "Необходимы для правильной работы веб-сайта.",
    analyticsCookies: "Аналитические файлы cookie",
    analyticsCookiesDesc: "Помогают нам понять, как посетители взаимодействуют с сайтом.",
    adCookies: "Рекламные файлы cookie",
    adCookiesDesc: "Используются нами и нашими партнерами (например, Google) для показа персонализированной рекламы.",
    close: "Закрыть"
  },
  tr: {
    title: "Gizliliğinize değer veriyoruz",
    description: "Biz ve ortaklarımız, cihazınızdaki bilgileri saklamak ve/veya bunlara erişmek için çerezler kullanırız. Bu, kişiselleştirilmiş reklamlar ve içerik sunmak, reklam ve içerik performansını ölçmek ve kitle analizleri elde etmek için kullanılır.",
    acceptAll: "Tümünü Kabul Et",
    rejectAll: "Gerekli Olmayanları Reddet",
    managePreferences: "Tercihleri Yönet",
    savePreferences: "Tercihleri Kaydet",
    essentialCookies: "Temel Çerezler (Gerekli)",
    essentialCookiesDesc: "Web sitesinin düzgün çalışması için gereklidir.",
    analyticsCookies: "Analitik Çerezleri",
    analyticsCookiesDesc: "Ziyaretçilerin siteyle nasıl etkileşimde bulunduğunu anlamamıza yardımcı olur.",
    adCookies: "Reklam Çerezleri",
    adCookiesDesc: "Bizim ve ortaklarımızın (Google gibi) kişiselleştirilmiş reklamlar sunması için kullanılır.",
    close: "Kapat"
  }
};

for (const [lang, texts] of Object.entries(translations)) {
  const filePath = path.join(process.cwd(), 'messages', `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data.Consent = texts;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`Updated Consent in ${lang}.json`);
  }
}
