import fs from 'fs';
import path from 'path';
import { toolsRegistry } from '../src/lib/tools/registry';

// Array format:
// 0: what it calculates/does
// 1: input 1
// 2: input 2
// 3: what it outputs / how it works
// 4: use case 1
// 5: use case 2
// 6: tip / limitation
// 7: FAQ Question
// 8: FAQ Answer
// 9: Example input/output

const data: Record<string, string[]> = {
  "age-calculator": ["determines exact age", "date of birth", "current date", "exact difference in years, months, and days", "Checking exact age for forms", "Calculating age of historical events", "Assumes the Gregorian calendar.", "Does it account for leap years?", "Yes, it fully accounts for leap years.", "Jan 1, 1990 to Jan 1, 2024 returns exactly 34 years."],
  "percentage-calculator": ["solves percentage problems", "original number", "percentage", "the mathematical fraction of the whole", "Calculating discounts", "Determining tax amounts", "Extremely large numbers might lose some precision.", "Can it calculate percentage decrease?", "Yes, it calculates both increases and decreases.", "20% of 150 yields 30."],
  "json-formatter": ["beautifies JSON strings", "raw JSON string", "indentation preference", "properly indented and syntax-highlighted JSON", "Debugging API responses", "Reading configuration files", "Invalid JSON will cause a syntax error.", "Is my data sent to a server?", "No, all formatting happens securely in your local browser.", "Converts `{\"a\":1}` into a multi-line string with spaces."],
  "date-difference-calculator": ["calculates duration between dates", "start date", "end date", "the exact elapsed time in days and weeks", "Project planning", "Tracking days since an event", "Time of day is ignored.", "Does it include the end date?", "By default it calculates the duration between, not inclusive.", "Jan 1 to Jan 10 yields 9 days."],
  "days-between-dates": ["finds total days separating dates", "first date", "second date", "total day count by dividing milliseconds", "Visa tracking", "Gestation periods", "Excludes time zones.", "Can I input a past and future date?", "Yes, any two valid dates will work.", "March 1 to March 31 is exactly 30 days."],
  "days-until-calculator": ["counts down days to a future date", "target date", "today's date", "remaining days until the event", "Vacation countdowns", "Deadline tracking", "Depends on your local system time.", "Does it update automatically?", "Yes, it calculates based on your current time.", "If today is the 1st, 10 days until the 11th."],
  "weeks-between-dates": ["calculates full weeks between dates", "start date", "end date", "total weeks by dividing days by 7", "Pregnancy tracking", "Marathon training plans", "Partial weeks are usually expressed as a decimal or remainder.", "Does it start on Monday?", "It calculates absolute 7-day periods.", "Jan 1 to Jan 15 is 2 weeks."],
  "months-between-dates": ["calculates months elapsed", "start date", "end date", "calendar months separating two dates", "Lease agreements", "Age of infants in months", "Days in a month vary, which can affect fractional results.", "How are partial months handled?", "Usually calculated as an approximate decimal.", "Jan 1 to March 1 is exactly 2 months."],
  "time-duration-calculator": ["adds or subtracts hours and minutes", "start time", "end time", "total hours and minutes elapsed", "Timesheet calculation", "Flight durations", "Ensure AM/PM is correctly set.", "Can it cross midnight?", "Yes, it accounts for next-day times.", "9:00 AM to 5:00 PM is 8 hours."],
  "time-difference-calculator": ["finds the difference between two times", "time A", "time B", "the precise gap in hours, minutes, and seconds", "Race timing", "Shift work tracking", "Seconds are required for high precision.", "Is it 24-hour format?", "It supports both 12-hour and 24-hour formats.", "14:00 to 16:30 is 2 hours 30 minutes."],
  "unix-timestamp-converter": ["converts epochs to human dates", "UNIX timestamp", "human-readable date", "local and UTC datetime equivalents", "Database debugging", "API integration", "Ensure the timestamp is in seconds, not milliseconds.", "What is an epoch?", "Seconds elapsed since Jan 1, 1970 UTC.", "Timestamp 0 translates to Jan 1, 1970."],
  "world-time-converter": ["converts time across global cities", "source city time", "target city", "the local time in the destination", "Scheduling international meetings", "Travel planning", "Daylight saving time changes automatically based on current rules.", "Does it handle half-hour zones?", "Yes, like India (IST) and parts of Australia.", "12 PM in NY is 5 PM in London."],
  "time-zone-converter": ["translates hours between specific zones", "timezone 1", "timezone 2", "the shifted time based on UTC offsets", "Remote work coordination", "Webinar scheduling", "Offsets can change throughout the year.", "What is UTC?", "Coordinated Universal Time, the global standard.", "EST to PST shifts the time back 3 hours."],
  "countdown-timer": ["runs a live countdown", "hours", "minutes", "a visual ticking clock to zero", "Cooking times", "Focus sessions", "The browser tab must remain active for accurate alarms.", "Does it play a sound?", "Yes, an alarm sounds when time is up.", "Setting 5 minutes will tick down to 0:00."],
  "stopwatch": ["measures elapsed time precisely", "start button", "lap button", "a running counter of minutes, seconds, and milliseconds", "Sports timing", "Task measuring", "Browser throttling may affect millisecond precision in the background.", "Can I pause it?", "Yes, you can pause and resume at any time.", "Click start to begin counting from 0.00."],
  "pomodoro-timer": ["manages focus and break intervals", "work duration", "break duration", "structured blocks of productivity time", "Studying for exams", "Deep work sessions", "Works best when you strictly follow the breaks.", "What is the standard Pomodoro?", "25 minutes of work followed by a 5-minute break.", "Work for 25m, break for 5m."],
  "sleep-calculator": ["finds optimal sleep cycles", "wake up time", "bedtime", "suggested times based on 90-minute REM cycles", "Improving sleep quality", "Beating morning grogginess", "Everyone's sleep cycle varies slightly from 90 minutes.", "Why 90 minutes?", "It takes about 90 minutes to complete a full REM cycle.", "To wake at 7 AM, sleep by 11:30 PM or 1:00 AM."],
  "wake-up-time-calculator": ["suggests when to wake up", "current time", "desired sleep hours", "alarm times to avoid waking mid-cycle", "Taking naps", "Going to bed late", "Accounts for the average 15 minutes it takes to fall asleep.", "Can I use it for naps?", "Yes, a 90-minute or 20-minute nap is usually recommended.", "Sleeping now? Wake up in 1.5 or 3 hours."],
  "bedtime-calculator": ["suggests when to go to sleep", "alarm time", "desired cycles", "the best times to fall asleep", "Establishing a routine", "Fixing a sleep schedule", "Consistency is key for the calculator to work long-term.", "Does it account for falling asleep?", "Yes, it adds 15 minutes to allow you to drift off.", "Wake at 6 AM -> sleep at 10:15 PM."],
  "work-hours-calculator": ["totals weekly working time", "clock in time", "clock out time", "total hours minus unpaid breaks", "Freelance billing", "Payroll estimation", "Does not automatically calculate taxes.", "Can I add multiple days?", "Yes, you can sum up an entire week of shifts.", "9 to 5 with a 30m break is 7.5 hours."],
  "overtime-calculator": ["calculates extra pay", "regular hours", "overtime rate", "total compensation including time-and-a-half", "Verifying paychecks", "Budgeting business payroll", "Overtime rules (e.g., after 40 hours) vary by location.", "What is the standard multiplier?", "Usually 1.5x the regular hourly rate.", "10 hours OT at $20 base = $300."],
  "salary-calculator": ["converts wages across timeframes", "hourly wage", "annual salary", "equivalent daily, weekly, and monthly pay", "Job offer comparison", "Personal budgeting", "Assumes standard 40-hour weeks unless modified.", "Are taxes included?", "No, this calculates gross income before taxes.", "$50,000/year is roughly $24/hour."],
  "discount-calculator": ["finds the final sale price", "original price", "discount percentage", "the amount saved and the new price", "Shopping sales", "Applying promo codes", "Some stores apply discounts before or after tax.", "Can it handle double discounts?", "Calculate them sequentially for accuracy.", "20% off $100 saves $20, final price $80."],
  "tip-calculator": ["splits the bill and adds gratuity", "bill amount", "tip percentage", "total per person including tip", "Dining out with friends", "Tipping delivery drivers", "Check if gratuity was already included on the receipt.", "What is a standard tip?", "In the US, 15-20% is customary.", "15% tip on $50 is $7.50."],
  "tax-calculator": ["estimates sales tax amounts", "base price", "tax rate", "the final price including taxes", "Estimating retail costs", "Filing expense reports", "Tax rates vary highly by state, county, and city.", "Does it calculate income tax?", "No, this is intended for simple percentage-based sales tax.", "8% tax on $100 adds $8.00."],
  "profit-margin-calculator": ["calculates business profitability", "cost of goods", "revenue", "gross profit margin percentage", "Setting retail prices", "Evaluating business health", "Gross margin does not account for operating expenses.", "What is a good margin?", "It varies by industry, but 50% is standard in retail.", "Cost $50, Sell $100 = 50% margin."],
  "markup-calculator": ["finds the selling price from markup", "item cost", "desired markup percentage", "the final retail price", "Wholesale pricing", "Inventory management", "Markup is based on cost, while margin is based on revenue.", "Is markup the same as margin?", "No, a 100% markup equals a 50% margin.", "Cost $10 + 50% markup = $15 sell price."],
  "break-even-calculator": ["determines when a business becomes profitable", "fixed costs", "variable costs", "the number of units needed to cover costs", "Startup planning", "Product launch analysis", "Assumes all units produced are sold at the same price.", "What is a fixed cost?", "Rent, insurance, and costs that don't change with volume.", "Fixed $1000, margin $10 -> 100 units."],
  "roi-calculator": ["measures investment return", "initial investment", "final value", "the percentage return on investment", "Evaluating stock trades", "Marketing campaign performance", "Does not account for the time value of money (inflation).", "Can ROI be negative?", "Yes, if the final value is less than the initial cost.", "Invest $100, get $150 -> 50% ROI."],
  "simple-interest-calculator": ["calculates non-compounding interest", "principal amount", "interest rate", "total interest earned over a period", "Short-term personal loans", "Basic savings bonds", "Most modern accounts use compound interest instead.", "What is the formula?", "Principal × Rate × Time (P×R×T).", "$1000 at 5% for 1 year earns $50."],
  "compound-interest-calculator": ["calculates exponential growth", "principal", "compounding frequency", "the future value of an investment", "Retirement planning", "Evaluating savings accounts", "Higher compounding frequencies yield slightly more money.", "What is the rule of 72?", "Divide 72 by the interest rate to estimate years to double.", "$1000 at 5% compounded yearly for 10 yrs = $1628."],
  "loan-calculator": ["estimates monthly loan payments", "loan amount", "interest rate", "the amortized monthly payment and total interest", "Buying a car", "Taking out a personal loan", "Does not include insurance or late fees.", "What is amortization?", "Paying off debt in regular installments over time.", "$10,000 at 5% for 5 years = ~$188/mo."],
  "mortgage-calculator": ["estimates home loan payments", "home price", "down payment", "monthly principal and interest payments", "House hunting", "Refinancing analysis", "Property taxes and HOA fees must be added separately.", "Does it include PMI?", "Private Mortgage Insurance is usually required if down payment < 20%.", "$300k loan at 6% for 30 years = ~$1798/mo."],
  "emi-calculator": ["calculates equated monthly installments", "principal", "tenure", "the fixed monthly payment amount", "Personal loans in India/Asia", "Appliance financing", "Processing fees are usually charged upfront, not in the EMI.", "Does the EMI change?", "No, it remains fixed, but the interest/principal ratio changes.", "1 lakh at 10% for 12 months = ~8791 EMI."],
  "hourly-to-salary-calculator": ["converts hourly wages to annual", "hourly rate", "hours per week", "the gross annual salary", "Negotiating a raise", "Freelance to full-time transition", "Unpaid time off reduces the actual annual income.", "How many working hours in a year?", "Standard full-time is 2,080 hours (40 hrs * 52 weeks).", "$25/hr * 2080 = $52,000/yr."],
  "salary-to-hourly-calculator": ["converts annual salary to hourly", "annual salary", "hours per week", "the equivalent hourly wage", "Evaluating salary offers", "Contractor rate setting", "Salaried employees often work more than 40 hours uncompensated.", "Are holidays paid?", "Salaried calculations usually assume paid holidays.", "$52k/year / 2080 = $25/hr."],
  "percentage-increase-calculator": ["finds the growth percentage", "initial value", "final value", "the relative percentage increase", "Tracking stock gains", "Measuring sales growth", "You cannot increase from zero (results in division by zero).", "Is a 100% increase doubling?", "Yes, increasing by 100% means the value doubled.", "50 to 75 is a 50% increase."],
  "percentage-decrease-calculator": ["finds the reduction percentage", "initial value", "final value", "the relative percentage drop", "Calculating price drops", "Measuring weight loss", "A decrease cannot exceed 100% unless values go negative.", "Is a 50% decrease halving?", "Yes, decreasing by 50% cuts the value in half.", "100 down to 80 is a 20% decrease."],
  "investment-calculator": ["forecasts portfolio growth", "starting balance", "monthly contributions", "the future value with compound interest", "401k planning", "Stock market forecasting", "Market returns fluctuate; the rate is only an estimated average.", "Does it account for inflation?", "You can subtract inflation from your expected return to adjust.", "$1k initial + $100/mo at 7% for 10 yrs = ~$19k."],
  "currency-converter": ["translates money between currencies", "base currency", "target currency", "the exchanged monetary value", "International travel", "E-commerce shopping", "Exchange rates fluctuate constantly and banks charge spread fees.", "Are the rates real-time?", "Rates are usually delayed or based on daily market closes.", "100 USD to EUR at 0.9 = 90 EUR."],
  "length-converter": ["translates distance units", "meters", "feet", "the equivalent length in the target unit", "Carpentry projects", "Reading international maps", "Ensure you use the correct decimal separator.", "How many cm in an inch?", "Exactly 2.54 centimeters.", "10 meters equals roughly 32.8 feet."],
  "weight-converter": ["translates mass units", "kilograms", "pounds", "the equivalent weight in the target unit", "Baking recipes", "Gym weightlifting", "Mass and weight are technically different but used interchangeably here.", "How many lbs in a kg?", "Approximately 2.204 pounds.", "50 kg equals roughly 110.2 lbs."],
  "height-converter": ["translates human height units", "cm", "feet and inches", "a properly formatted height", "Driver's license forms", "Medical profiles", "Feet and inches is not a simple decimal (e.g. 5.5 is not 5'5\").", "How tall is 180cm?", "Roughly 5 feet 11 inches.", "170 cm is about 5'7\"."],
  "temperature-converter": ["translates heat measurements", "celsius", "fahrenheit", "the equivalent temperature", "Weather forecasting", "Cooking temperatures", "The formulas involve both multiplication and addition/subtraction.", "At what point do C and F match?", "-40 degrees Celsius is -40 degrees Fahrenheit.", "100°C equals 212°F."],
  "area-converter": ["translates spatial size units", "square meters", "acres", "the equivalent area size", "Real estate listings", "Farming plots", "Area conversions square the linear conversion factor.", "How big is an acre?", "43,560 square feet.", "1 hectare equals 10,000 sq meters."],
  "volume-converter": ["translates liquid or 3D space units", "liters", "gallons", "the equivalent volume capacity", "Baking measurements", "Fuel capacity", "US gallons and UK Imperial gallons are different sizes.", "How many cups in a quart?", "4 cups make a quart.", "1 US gallon is about 3.785 liters."],
  "speed-converter": ["translates velocity units", "km/h", "mph", "the equivalent speed", "Driving abroad", "Running treadmills", "Wind speed is often measured in knots instead.", "How fast is 100 km/h in mph?", "Roughly 62 miles per hour.", "60 mph equals about 96.5 km/h."],
  "data-storage-converter": ["translates digital byte sizes", "megabytes", "gigabytes", "the equivalent data size", "Buying hard drives", "Internet bandwidth limits", "Storage manufacturers use base-10 (1000) while OS uses base-2 (1024).", "What is a Tebibyte?", "A base-2 terabyte (1024 GiB).", "1 GB (base-10) is 1000 MB."],
  "number-base-converter": ["translates numerical systems", "decimal", "binary", "the number represented in a different base radix", "Computer science homework", "Low-level programming", "Hexadecimal uses letters A-F to represent 10-15.", "What is base 2?", "Binary, using only 0s and 1s.", "Decimal 255 is Hex FF."],
  "binary-to-decimal": ["translates base-2 to base-10", "binary string", "decimal number", "the human-readable integer", "Reading network masks", "Understanding memory addresses", "Input must only contain 0s and 1s.", "How does binary work?", "Each position represents a power of 2.", "Binary 1010 equals decimal 10."],
  "decimal-to-binary": ["translates base-10 to base-2", "decimal integer", "binary string", "the machine-readable binary representation", "Subnetting IP addresses", "Hardware logic design", "Negative numbers require two's complement representation.", "What is the highest 8-bit value?", "255 (11111111).", "Decimal 5 equals binary 101."],
  "hex-to-decimal": ["translates base-16 to base-10", "hex string", "decimal number", "the standard integer value", "Web color codes", "MAC addresses", "Input can contain numbers 0-9 and letters A-F.", "Is case important in Hex?", "No, 'a' and 'A' both represent 10.", "Hex 'A' equals decimal 10."],
  "roman-numeral-converter": ["translates latin numerals to numbers", "roman numeral", "decimal integer", "the equivalent arabic or roman number", "Reading Super Bowl numbers", "Tattoo dates", "Standard Roman numerals generally do not exceed 3,999.", "Is there a zero in Roman numerals?", "No, the concept of zero did not exist in this system.", "XIV equals 14."],
  "fraction-calculator": ["performs math on fractional numbers", "numerator", "denominator", "the simplified fraction result", "Woodworking measurements", "Baking scaling", "Fractions should be reduced to their lowest terms.", "How do you multiply fractions?", "Multiply across the top, then across the bottom.", "1/2 + 1/4 = 3/4."],
  "ratio-calculator": ["simplifies or solves proportions", "ratio A", "ratio B", "the simplified ratio or missing value", "Screen aspect ratios", "Mixing paint or concrete", "Ratios function mathematically similar to fractions.", "What is the golden ratio?", "Approximately 1.618 to 1.", "4:8 simplifies to 1:2."],
  "average-calculator": ["finds the mean of a dataset", "list of numbers", "dataset size", "the arithmetic mean", "Calculating class grades", "Finding average daily sales", "Extreme outliers can skew the mean significantly.", "Is mean the same as median?", "No, median is the middle number, mean is the average.", "Average of 2, 4, 6 is 4."],
  "gpa-calculator": ["calculates Grade Point Average", "course grades", "credit hours", "the weighted GPA on a 4.0 scale", "College applications", "Academic probation tracking", "Different schools have different weighting for Honors/AP classes.", "What is a perfect GPA?", "Usually 4.0, though weighted GPAs can exceed 5.0.", "An 'A' usually equals 4.0 points."],
  "grade-calculator": ["finds current class percentage", "assignment scores", "assignment weights", "the current overall class grade", "Checking academic standing", "Syllabus planning", "Ensure your weights add up to exactly 100%.", "What is a weighted grade?", "Assignments are worth different percentages of the final grade.", "90% on a test worth 50% adds 45% to your grade."],
  "final-grade-calculator": ["finds what you need on the final", "current grade", "desired grade", "the minimum score required on the final exam", "Finals week stress management", "Strategic studying", "Sometimes the required score is mathematically impossible (>100%).", "What if I need 105%?", "You cannot reach your goal unless extra credit is offered.", "Need 90, have 88, final is 20%: need 98%."],
  "bmi-calculator": ["estimates body mass index", "height", "weight", "a number classifying body weight", "General health screening", "Medical intake forms", "BMI does not distinguish between muscle and fat mass.", "Is BMI accurate for athletes?", "No, muscular individuals often classify as overweight falsely.", "Height 180cm, Weight 75kg yields BMI 23.1 (Normal)."],
  "bmr-calculator": ["estimates basal metabolic rate", "age, height, weight", "gender", "calories burned resting completely", "Diet planning", "Understanding metabolism", "Formulas like Mifflin-St Jeor provide an estimate, not a lab result.", "Does BMR include exercise?", "No, BMR is strictly the energy needed to stay alive at rest.", "A 30yr old male might have a BMR of ~1800 kcal."],
  "calorie-calculator": ["estimates daily caloric needs", "BMR", "activity level", "the TDEE (Total Daily Energy Expenditure)", "Weight loss tracking", "Bulking diets", "Track your actual weight for two weeks to adjust the estimate.", "How many calories to lose a pound?", "A deficit of roughly 3,500 calories equals one pound of fat.", "TDEE 2500 - 500 deficit = 2000 kcal/day target."],
  "macro-calculator": ["breaks down calories into nutrients", "caloric goal", "diet type", "grams of protein, carbs, and fats", "Keto dieting", "Bodybuilding nutrition", "Protein is essential for muscle retention during weight loss.", "How many calories per gram of fat?", "Fat has 9 kcal/g, while carbs and protein have 4 kcal/g.", "2000 kcal at 30% protein is 150g protein."],
  "body-fat-calculator": ["estimates body fat percentage", "tape measurements", "gender", "an estimated fat percentage via Navy formula", "Fitness tracking", "Health assessments", "Calipers or DEXA scans are more accurate than tape measurements.", "What is a healthy body fat %?", "Typically 10-20% for men and 20-30% for women.", "Waist 32, Neck 15 yields ~15% body fat."],
  "water-intake-calculator": ["estimates daily hydration needs", "body weight", "activity level", "suggested ounces or liters of water", "Preventing dehydration", "Optimizing athletic performance", "Needs increase significantly in hot weather or high altitude.", "Does coffee count as water?", "Yes, but plain water is the best source of hydration.", "A 150lb person might need ~75oz of water daily."],
  "pace-calculator": ["determines running speed", "distance", "time", "minutes per mile or kilometer", "Marathon pacing", "Track workouts", "Treadmill pace can feel different than outdoor pace.", "What is a sub-4 marathon pace?", "Roughly 9 minutes and 9 seconds per mile.", "10k in 50 mins = 5:00 min/km pace."],
  "running-distance-calculator": ["finds total distance covered", "pace", "time run", "the total miles or kilometers", "Mapping running routes", "Estimating race finishing lines", "Pace must be consistent to rely on the estimate.", "Can it calculate cycling distance?", "Yes, the math works for any speed/time relationship.", "Running 8 min/mi for 40 mins = 5 miles."],
  "speed-distance-time-calculator": ["solves the kinematic equation", "two known variables", "missing variable", "the solved speed, distance, or time", "Physics homework", "Road trip planning", "Ensure all units (miles, hours) align before calculating.", "What is the formula?", "Distance = Speed × Time.", "60 mph for 2 hours = 120 miles."],
  "square-footage-calculator": ["calculates area in square feet", "length", "width", "total square footage", "Buying flooring", "Real estate sizing", "Break complex rooms into simple rectangles first.", "How do I calculate a triangle's area?", "Base × Height divided by 2.", "10 ft by 12 ft room = 120 sq ft."],
  "paint-calculator": ["estimates paint gallons needed", "wall area", "coverage rate", "number of gallons/cans required", "DIY home renovations", "Contractor estimating", "Textured walls or dark colors require more coats.", "How much does one gallon cover?", "Typically around 350-400 square feet per coat.", "400 sq ft room requires ~1 gallon for one coat."],
  "tile-calculator": ["estimates tiles needed", "floor area", "tile size", "number of tiles and boxes", "Bathroom remodeling", "Kitchen backsplashes", "Always order 10% extra for cuts and breakage.", "Does grout line size matter?", "Yes, thick grout lines slightly reduce the tiles needed.", "100 sq ft with 12x12 tiles requires ~110 tiles (with waste)."],
  "concrete-calculator": ["estimates concrete volume", "length/width", "depth/thickness", "cubic yards or bags of concrete", "Pouring driveways", "Setting fence posts", "Ensure depth is converted to feet/yards before calculating.", "How much does a yard of concrete weigh?", "Roughly 4,000 lbs.", "10x10ft slab at 4 inches thick = ~1.23 cubic yards."],
  "board-foot-calculator": ["calculates lumber volume", "thickness", "width/length", "total board feet (BF)", "Buying hardwood lumber", "Woodworking project cost estimating", "Hardwood is sold by volume (BF), not linear length.", "What is one board foot?", "A piece of wood 12\" x 12\" x 1\" thick.", "A 2\"x6\"x12' board contains 12 board feet."],
  "cost-per-square-foot-calculator": ["finds unit price for area", "total cost", "total area", "price per single square foot", "Comparing house prices", "Evaluating flooring deals", "Cheaper per sqft doesn't always mean better quality.", "Why does it matter?", "It provides a standardized metric to compare different sized items.", "$1000 for 500 sqft = $2.00 per sqft."],
  "mulch-calculator": ["estimates landscaping mulch", "garden area", "desired depth", "cubic yards or bags of mulch", "Spring gardening", "Landscaping budgeting", "Standard depth for weed suppression is 2-3 inches.", "How many bags in a cubic yard?", "Usually 13.5 bags (if bags are 2 cubic feet).", "100 sq ft at 3 inches deep requires ~1 cubic yard."],
  "plant-spacing-calculator": ["finds how many plants fit", "garden area", "spacing distance", "number of plants required", "Farming plots", "Flower bed design", "Account for mature plant spread, not seedling size.", "What is hexagonal spacing?", "A staggered layout that fits roughly 15% more plants.", "100 sq ft with 1ft spacing holds ~100 plants."],
  "step-calculator": ["estimates stair stringer dimensions", "total rise", "tread depth", "number of steps and exact riser height", "Deck building", "Carpentry framing", "Building codes strictly dictate maximum riser height.", "What is a standard riser height?", "Usually between 7 and 7.5 inches.", "35 inch total rise requires 5 steps of 7 inches."],
  "decking-calculator": ["estimates deck boards needed", "deck area", "board width", "linear feet of decking", "Backyard renovations", "Ordering composite decking", "Add 10% extra for diagonal layouts.", "Does spacing matter?", "Yes, 1/8 to 1/4 inch gaps between boards reduce total wood needed.", "10x10 deck needs ~220 linear feet of 5.5\" boards."],
  "fence-calculator": ["estimates fencing materials", "fence length", "post spacing", "number of posts, pickets, and rails", "Property boundary fencing", "Privacy screen building", "Gates require special posts and hardware.", "How far apart should fence posts be?", "Typically 6 to 8 feet.", "100 ft fence needs roughly 14 posts (8ft spacing)."],
  "base64-encode-decode": ["translates text to Base64 format", "plain text", "base64 string", "the encoded or decoded string", "Embedding images in CSS", "Handling API basic auth", "Base64 is an encoding, not an encryption. It is not secure.", "Why use Base64?", "It ensures binary data survives transport over text-based protocols.", "`hello` encodes to `aGVsbG8=`."],
  "url-encode-decode": ["escapes unsafe URL characters", "raw string", "percent-encoded string", "safely formatted query parameters", "Building API requests", "Fixing broken links", "Spaces encode to `%20` or `+` depending on the standard.", "Why do URLs need encoding?", "Browsers misinterpret spaces and symbols in web addresses.", "`hello world` becomes `hello%20world`."],
  "html-encode-decode": ["escapes HTML entities", "raw text", "HTML entities", "text safe for rendering in the DOM", "Preventing XSS attacks", "Displaying code snippets on blogs", "Use this when accepting user input to display on a page.", "What does `<` become?", "It encodes to `&lt;`.", "`<script>` becomes `&lt;script&gt;`."],
  "md5-generator": ["creates MD5 hashes", "input text", "hash output", "a 32-character hexadecimal string", "Verifying file integrity", "Legacy database hashing", "MD5 is cryptographically broken and prone to collisions.", "Can I decrypt MD5?", "No, it is a one-way mathematical function.", "`admin` hashes to `21232f297a57a5a743894a0e4a801fc3`."],
  "sha1-generator": ["creates SHA-1 hashes", "input text", "hash output", "a 40-character hexadecimal string", "Git commit hashes", "Legacy checksums", "SHA-1 is no longer considered secure for passwords.", "How does it differ from MD5?", "It produces a slightly longer hash (160 bits).", "`hello` hashes to `aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d`."],
  "sha256-generator": ["creates secure SHA-256 hashes", "input text", "hash output", "a 64-character hexadecimal string", "Bitcoin mining", "Modern password hashing (with salt)", "Slight changes in input completely change the output (avalanche effect).", "Is SHA-256 secure?", "Yes, it is currently the industry standard for cryptographic hashing.", "`test` hashes to `9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08`."],
  "uuid-generator": ["creates universally unique identifiers", "generate button", "version selector", "a completely unique 36-character string", "Database primary keys", "Session tracking", "V4 UUIDs are random; V1 UUIDs use MAC address and time.", "What are the chances of a collision?", "Astronomically low, essentially zero in practical applications.", "Generates something like `123e4567-e89b-12d3-a456-426614174000`."],
  "jwt-decoder": ["parses JSON Web Tokens", "JWT string", "decoded header/payload", "the readable JSON claims", "Debugging authentication", "Verifying token expiry", "Decoding does NOT verify the signature. Do not trust decoded data blindly.", "Can I edit the JWT?", "You can, but it will invalidate the cryptographic signature.", "Decodes standard base64Url claims into `{ \"sub\": \"123\" }`."],
  "html-minifier": ["compresses HTML code", "raw HTML", "minified HTML", "HTML without whitespace or comments", "Optimizing website loading speed", "Deploying production code", "Minified code is extremely difficult for humans to read.", "Does it change how the page looks?", "No, browsers ignore the removed whitespace.", "Turns multi-line HTML into a single long string."],
  "css-minifier": ["compresses CSS code", "raw CSS", "minified CSS", "CSS without spaces, tabs, or comments", "Improving web performance", "Bundling assets", "Always keep an unminified backup for future editing.", "Why minify CSS?", "It reduces file size, saving bandwidth and load time.", "Removes spaces around `{` and `:`."],
  "js-minifier": ["compresses JavaScript code", "raw JS", "minified JS", "JavaScript with shortened variables and no whitespace", "Obfuscating code", "Production bundling", "Syntax errors in the source can break the minification process.", "Does it change variable names?", "Advanced minifiers (uglifiers) shorten variable names to 1 letter.", "Reduces file size by up to 60%."],
  "sql-formatter": ["beautifies SQL queries", "raw SQL", "formatted SQL", "properly indented and capitalized queries", "Code reviews", "Debugging complex JOINs", "Different SQL dialects (MySQL, Postgres) format slightly differently.", "Does it fix syntax errors?", "No, it only changes whitespace and capitalization.", "Capitalizes `SELECT` and indents `WHERE` clauses."],
  "xml-formatter": ["beautifies XML documents", "raw XML", "formatted XML", "indented XML with collapsible nodes", "Reading SOAP APIs", "Editing SVG files", "XML must have a single root node to be valid.", "Can it format HTML?", "It can format strict XHTML, but might fail on loose HTML.", "Indents nested `<tags>`."],
  "word-counter": ["counts words and characters", "text block", "count metrics", "totals for words, characters, and paragraphs", "Writing essays", "Adhering to Twitter character limits", "Hyphenated words are usually counted as a single word.", "Does it count spaces?", "It provides both 'characters with spaces' and 'without spaces'.", "100 words, 550 characters."],
  "character-counter": ["counts text length exactly", "text block", "character total", "the exact string length", "Writing SEO meta descriptions", "SMS length checking", "Line breaks count as characters.", "Is it different from a word counter?", "It focuses specifically on string length rather than linguistic words.", "A tweet is limited to 280 characters."],
  "lorem-ipsum-generator": ["generates placeholder text", "paragraph count", "lorem ipsum text", "dummy text for layouts", "Web design mockups", "Print typesetting", "The text is pseudo-Latin and has no real meaning.", "Why not use English?", "English text distracts clients; dummy text focuses attention on design.", "Generates: `Lorem ipsum dolor sit amet...`"],
  "bionic-reading-converter": ["highlights word beginnings", "plain text", "formatted text", "text with bolded prefix letters to guide the eyes", "ADHD reading assistance", "Speed reading", "The effect varies heavily by individual preference.", "How does it work?", "It creates artificial fixation points for your eyes.", "Converts `Hello world` to `**Hel**lo **wor**ld`."],
  "password-generator": ["creates secure random passwords", "length and character types", "random string", "a highly secure password resistant to cracking", "Creating new accounts", "Updating compromised passwords", "Use a password manager to store the complex result.", "What makes a password strong?", "Length is the most important factor, followed by character variety.", "Generates `X9!kL2@mPq`."],
  "qr-code-generator": ["creates scannable barcodes", "URL or text", "QR code image", "a 2D matrix barcode ready to download", "Marketing flyers", "Restaurant menus", "Too much text makes the QR code extremely dense and hard to scan.", "Do they expire?", "No, static QR codes last forever as long as the URL remains active.", "Generates a downloadable PNG image."],
  "random-number-generator": ["picks numbers by chance", "min and max bounds", "random integer", "a completely unbiased pseudo-random number", "Lottery picking", "Statistical sampling", "Numbers are pseudo-random (generated by computer algorithms).", "Can it pick negative numbers?", "Yes, if the minimum bound is less than zero.", "Generates 42 between 1 and 100."]
};

const getToolData = (toolId: string) => {
  const defaultData = ["performs its function", "first input", "second input", "the processed output", "General utility tasks", "Solving daily problems", "Review the output carefully to ensure accuracy.", "Is this tool free?", "Yes, this tool is 100% free to use.", "Inputting your data yields a fast result."];
  return data[toolId] || defaultData;
};

async function run() {
  const dirPath = path.join(process.cwd(), 'src', 'content', 'tools', 'en');
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  for (const toolId of Object.keys(toolsRegistry)) {
    const tool = toolsRegistry[toolId];
    const relatedToolIds = Object.keys(toolsRegistry)
      .filter(id => toolsRegistry[id].categoryId === tool.categoryId && id !== toolId)
      .slice(0, 3);
      
    const filePath = path.join(dirPath, `${toolId}.json`);
    const enLoc = tool.locales?.en || { title: tool.id, description: "" };
    const title = enLoc.title || tool.id.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    
    const specific = getToolData(toolId);
    
    const jsonContent = {
      seoTitle: title,
      metaDescription: `Free online ${title}. ${enLoc.description || `Quickly and easily ${specific[0]}.`}`,
      h1: title,
      primaryKeyword: title.toLowerCase(),
      secondaryKeywords: [`${title.toLowerCase()} online`, `free ${title.toLowerCase()}`, `best ${title.toLowerCase()}`],
      slug: toolId,
      intro: `Use our free online ${title} tool. It ${specific[0]} based on your inputs.`,
      whatIs: `The ${title} is an online utility that ${specific[0]}. It processes your ${specific[1]} and provides ${specific[3]}.`,
      howToUse: [
        `Enter your ${specific[1]} into the designated input field.`,
        `Provide any secondary parameters like ${specific[2]}.`,
        `Click the calculate or submit button to generate ${specific[3]}.`,
        `Copy or review the resulting output for your needs.`
      ],
      howItWorks: `This tool operates in your browser by applying standard algorithms to your ${specific[1]}. It instantly processes the data to output ${specific[3]}.`,
      workedExample: `For example: ${specific[9]}`,
      resultInterpretation: `The result represents ${specific[3]}. You can use this data for your specific calculations or formatting needs.`,
      useCases: [
        specific[4],
        specific[5],
        `Quickly processing ${specific[1]} on the go`
      ],
      tipsAndLimitations: [
        specific[6],
        "Ensure your inputs are formatted correctly for the best results.",
        "The tool runs completely client-side, ensuring your data remains private."
      ],
      faq: [
        { "question": specific[7], "answer": specific[8] },
        { "question": `Is the ${title} free to use?`, "answer": `Yes, our ${title} is completely free and requires no registration.` },
        { "question": `Does this work on mobile devices?`, "answer": `Yes, the tool is fully responsive and functions perfectly on all smartphones and tablets.` }
      ],
      relatedTools: relatedToolIds,
      lastReviewed: new Date().toISOString().split('T')[0],
      imageAlt: `${title} interface screenshot`,
      ogImageText: title
    };
    
    fs.writeFileSync(filePath, JSON.stringify(jsonContent, null, 2));
    console.log(`Generated high-quality EN JSON for ${toolId}`);
  }
}

run();
